import type { SeriesDetails } from '../types';

export const canalRibbons: SeriesDetails = {
    slug: "canal-ribbons",
  published: false,
    category: "Personal",
    title: "Canal Ribbons",
    year: 2024,
    location: "Meguro & Ebisu",
    palette: "color",
    focus: "urban",
    synopsis: "中目黒から品川へと続く運河沿いを歩き、夕景から夜景へ変わる瞬間を束ねたシリーズ。",
    lead: "代官山から中目黒、目黒川沿いの橋を渡りながら、街灯と車列が運河に描くリボンのような光跡を追いました。",
    story:
      "水面の反射を柔らかくするため偏光フィルターを調整しつつ、橋上では手すりを前ボケに入れて立体感を演出。夕暮れ時は1/60sまで落として人の流れを残し、夜は三脚不可の環境でもぶれないシャッタースピードを維持しました。",
    tags: ["Urban", "Night", "Waterfront"],
    cover: {
      src: "/content/series/personal/canal-ribbons/canal-ribbons-01.webp",
      alt: "代官山から中目黒へ続くライトと運河",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/content/series/personal/canal-ribbons/canal-ribbons-02.webp",
      alt: "代官山から中目黒へ続くライトと運河 2",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-01.webp",
        alt: "代官山から中目黒へ続くライトと運河",
        width: 2560,
        height: 1707,
        contentLocation: "Nakameguro, Tokyo, Japan",
        datePublished: "2024-09-13",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-02.webp",
        alt: "代官山から中目黒へ続くライトと運河 2",
        width: 2560,
        height: 1707,
        contentLocation: "Nakameguro, Tokyo, Japan",
        datePublished: "2024-09-13",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-03.webp",
        alt: "代官山から中目黒へ続くライトと運河 3",
        width: 2560,
        height: 1707,
        contentLocation: "Nakameguro, Tokyo, Japan",
        datePublished: "2024-09-13",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-04.webp",
        alt: "中目黒の高架下に差し込む夜の光",
        width: 2560,
        height: 1707,
        contentLocation: "Nakameguro, Tokyo, Japan",
        datePublished: "2024-09-13",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-05.webp",
        alt: "中目黒の高架下に差し込む夜の光 2",
        width: 2560,
        height: 1707,
        contentLocation: "Nakameguro, Tokyo, Japan",
        datePublished: "2024-09-13",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-06.webp",
        alt: "中目黒の高架下に差し込む夜の光 3",
        width: 2560,
        height: 1707,
        contentLocation: "Nakameguro, Tokyo, Japan",
        datePublished: "2024-09-13",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-07.webp",
        alt: "中目黒の高架下に差し込む夜の光 4",
        width: 2560,
        height: 1707,
        contentLocation: "Nakameguro, Tokyo, Japan",
        datePublished: "2024-09-13",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-08.webp",
        alt: "中目黒の高架下に差し込む夜の光 5",
        width: 2560,
        height: 1707,
        contentLocation: "Nakameguro, Tokyo, Japan",
        datePublished: "2024-09-13",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-09.webp",
        alt: "恵比寿から中目黒へ続く川沿いの歩道",
        width: 2560,
        height: 1707,
        contentLocation: "Ebisu to Nakameguro, Tokyo, Japan",
        datePublished: "2024-10-02",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-10.webp",
        alt: "恵比寿から中目黒へ続く川沿いの歩道 2",
        width: 2560,
        height: 1707,
        contentLocation: "Ebisu to Nakameguro, Tokyo, Japan",
        datePublished: "2024-10-02",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-11.webp",
        alt: "恵比寿から中目黒へ続く川沿いの歩道 3",
        width: 2048,
        height: 2560,
        contentLocation: "Ebisu to Nakameguro, Tokyo, Japan",
        datePublished: "2024-10-02",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-12.webp",
        alt: "目黒から品川へ続く線路脇のテールライト",
        width: 2048,
        height: 2560,
        contentLocation: "Meguro to Shinagawa, Tokyo, Japan",
        datePublished: "2025-06-07",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-13.webp",
        alt: "目黒から品川へ続く線路脇のテールライト 2",
        width: 1707,
        height: 2560,
        contentLocation: "Meguro to Shinagawa, Tokyo, Japan",
        datePublished: "2025-06-07",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-14.webp",
        alt: "笹塚から代々木へ続く歩道橋の光",
        width: 2560,
        height: 1707,
        contentLocation: "Sasazuka to Yoyogi, Tokyo, Japan",
        datePublished: "2025-02-01",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-15.webp",
        alt: "笹塚から代々木へ続く歩道橋の光 2",
        width: 2560,
        height: 1707,
        contentLocation: "Sasazuka to Yoyogi, Tokyo, Japan",
        datePublished: "2025-02-01",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-16.webp",
        alt: "笹塚から代々木へ続く歩道橋の光 3",
        width: 2048,
        height: 2560,
        contentLocation: "Sasazuka to Yoyogi, Tokyo, Japan",
        datePublished: "2025-02-01",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-17.webp",
        alt: "笹塚から代々木へ続く歩道橋の光 4",
        width: 2048,
        height: 2560,
        contentLocation: "Sasazuka to Yoyogi, Tokyo, Japan",
        datePublished: "2025-02-01",
      },
      {
        src: "/content/series/personal/canal-ribbons/canal-ribbons-18.webp",
        alt: "代々木公園の夕暮れ",
        width: 2560,
        height: 1707,
        contentLocation: "Yoyogi, Tokyo, Japan",
        datePublished: "2025-02-01",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 24-70mm F2.8 GM II" },
      { label: "Settings", value: "1/200s · F4 · ISO 400" },
    ],
    relatedCta: {
      heading: "街歩きロケのご相談",
      body: "運河沿いのロケーションでは、人の流れと街灯の配置を踏まえた絵作りを含めてご提案します。",
      href: "/services",
      label: "Servicesを見る",
    },
  };
