import type { SeriesDetails } from '../types';

export const elevatedCitylines: SeriesDetails = {
    slug: "elevated-citylines",
  published: false,
    category: "Personal",
    title: "Elevated Citylines",
    year: 2024,
    location: "Central Tokyo",
    palette: "color",
    focus: "urban",
    synopsis: "高層ビルや展望台から都市を俯瞰し、夜明け前後の街のレイヤーを切り取ったシリーズ。",
    lead: "新宿と皇居周辺を軸に、夜景からブルーアワーまでの時間帯でビル群と交通の流れを追いました。",
    story:
      "超広角と中望遠を切り替えながら、手持ちでの手ブレ限界と三脚不可の制約の中で露出を整え、ネオンと街灯の色を保つよう調整しています。",
    tags: ["Urban", "Night", "Viewpoint"],
    cover: {
      src: "/content/series/personal/elevated-citylines/elevated-citylines-01.webp",
      alt: "新宿高層ビル群を望む展望",
      width: 1707,
      height: 2560,
    },
    heroImage: {
      src: "/content/series/personal/elevated-citylines/elevated-citylines-02.webp",
      alt: "新宿高層ビル群を望む展望 2",
      width: 1707,
      height: 2560,
    },
    gallery: [
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-01.webp",
        alt: "新宿高層ビル群を望む展望",
        width: 1707,
        height: 2560,
        contentLocation: "Shinjuku, Tokyo, Japan",
        datePublished: "2024-10-15",
        caption: "展望の窓が夜景を切り取る。",
        statement:
          "展望台のガラス反射を抑えるため、黒いクロスでレンズ周りを覆いながら撮影しました。超広角で歪みが出ない角度を探り、街のラインが均等に広がるポイントに立っています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-02.webp",
        alt: "新宿高層ビル群を望む展望 2",
        width: 1707,
        height: 2560,
        contentLocation: "Shinjuku, Tokyo, Japan",
        datePublished: "2024-10-15",
        caption: "都市のラインが雲海のように重なる。",
        statement:
          "早朝の蒼が残る時間に露出を-0.5EVに抑え、ビル群の陰影を強調しました。雲の流れが均一になるまで待ち、三脚禁止のため肘を手すりに固定してブレを防いでいます。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-03.webp",
        alt: "新宿高層ビル群を望む展望 3",
        width: 1707,
        height: 2560,
        contentLocation: "Shinjuku, Tokyo, Japan",
        datePublished: "2024-10-15",
        caption: "交差する道路が光の格子を描く。",
        statement:
          "道路の交差が最も立体的に見える角度を探し、45mmで圧縮しました。車列の途切れを避けるため複数回露光を確認し、1/2秒で光跡を伸ばしています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-04.webp",
        alt: "新宿高層ビル群を望む展望 4",
        width: 2560,
        height: 1707,
        contentLocation: "Shinjuku, Tokyo, Japan",
        datePublished: "2024-10-15",
        caption: "夜明け前の蒼がビル群を包む。",
        statement:
          "空のグラデーションが残るタイミングに合わせ、ホワイトバランスを4000Kに固定しました。窓の明かりが灯るビルを選び、都市の密度が伝わる構図に整えています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-05.webp",
        alt: "新宿高層ビル群を望む展望 5",
        width: 1707,
        height: 2560,
        contentLocation: "Shinjuku, Tokyo, Japan",
        datePublished: "2024-10-15",
        caption: "高層のリズムが街の息を整える。",
        statement:
          "ビルの縦線が画面内で均等になるよう、足場を数センチずつ調整しました。露出を少しアンダーにし、外周の暗部が締まるようコントラストをコントロールしています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-06.webp",
        alt: "新宿の夜景と光跡",
        width: 2560,
        height: 1707,
        contentLocation: "Shinjuku, Tokyo, Japan",
        datePublished: "2024-10-17",
        caption: "ネオンの流れが街路を染める。",
        statement:
          "ネオンの切り替わりをメモし、色が滑らかに移ろう瞬間を待ちました。レンズフレアを抑えるためフードを密着させ、1/3秒で光の帯を滑らかに描いています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-07.webp",
        alt: "新宿の夜景と光跡 2",
        width: 2560,
        height: 1707,
        contentLocation: "Shinjuku, Tokyo, Japan",
        datePublished: "2024-10-17",
        caption: "交差点の光跡が都市の呼吸を描く。",
        statement:
          "歩行者信号のサイクルを合わせ、車列が整うタイミングでシャッターを切りました。雨上がりの路面が反射する位置を選び、都市の脈動を強調しています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-08.webp",
        alt: "新宿の夜景と光跡 3",
        width: 2560,
        height: 1707,
        contentLocation: "Shinjuku, Tokyo, Japan",
        datePublished: "2024-10-17",
        caption: "立体交差が光の帯を編む。",
        statement:
          "立体交差の高さが揃うよう、少し離れた建物から望遠で圧縮しました。ISOを抑えて長秒露光し、光跡が滑らかに繋がるよう1秒に設定しています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-09.webp",
        alt: "新宿の夜景と光跡 4",
        width: 2560,
        height: 1707,
        contentLocation: "Shinjuku, Tokyo, Japan",
        datePublished: "2024-10-17",
        caption: "車列のリズムが摩天楼を縁取る。",
        statement:
          "ヘッドライトが途切れない時間帯に合わせて再訪し、手持ちで1/4秒までブレを抑えました。画面端のビルが倒れないよう水平を慎重に合わせています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-10.webp",
        alt: "新宿の夜景と光跡 5",
        width: 2560,
        height: 1707,
        contentLocation: "Shinjuku, Tokyo, Japan",
        datePublished: "2024-10-17",
        caption: "夜雲に滲むビルが光を返す。",
        statement:
          "雲が低く降りてきた瞬間を狙い、露出を-0.7EVにして光の滲みを残しました。WBを少し暖めて、ビルの窓明かりが柔らかく見えるトーンに整えています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-11.webp",
        alt: "新宿中央公園の夜明け",
        width: 2560,
        height: 1707,
        contentLocation: "Shinjuku Chuo Park, Tokyo, Japan",
        datePublished: "2024-10-20",
        caption: "公園の木々が夜明けの蒼に滲む。",
        statement:
          "夜明け前の蒼時間に合わせ、F4で背景のビルを柔らかくぼかしました。手前の樹木が重ならない位置を探り、湿度を感じるコントラストに抑えています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-12.webp",
        alt: "新宿中央公園の夜明け 2",
        width: 1707,
        height: 2560,
        contentLocation: "Shinjuku Chuo Park, Tokyo, Japan",
        datePublished: "2024-10-20",
        caption: "噴水越しに朝の光が差し込む。",
        statement:
          "噴水のリズムを観察し、最も高く跳ね上がるタイミングで1/500秒に設定しました。逆光で飛沫が輝く位置を探し、露出をわずかにアンダーに抑えています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-13.webp",
        alt: "新宿中央公園の夜明け 3",
        width: 1707,
        height: 2560,
        contentLocation: "Shinjuku Chuo Park, Tokyo, Japan",
        datePublished: "2024-10-20",
        caption: "ベンチが眠気を含んだ光を浴びる。",
        statement:
          "ベンチを主役にするため望遠で圧縮し、背景のビルを柔らかく処理しました。人通りがない時間帯を選び、静けさが伝わるよう露出を抑えています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-14.webp",
        alt: "新宿中央公園の夜明け 4",
        width: 2560,
        height: 1707,
        contentLocation: "Shinjuku Chuo Park, Tokyo, Japan",
        datePublished: "2024-10-20",
        caption: "歩道のラインが都市の目覚めを導く。",
        statement:
          "歩道のラインが対角に走る構図を作り、ローアングルで奥行きを出しました。光が路面を滑る時間帯に合わせ、ハイライトを飛ばさないようヒストグラムを確認しています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-15.webp",
        alt: "皇居外苑のライトトレイル",
        width: 2560,
        height: 1707,
        contentLocation: "Imperial Palace Outer Garden, Tokyo, Japan",
        datePublished: "2025-02-28",
        caption: "堀のカーブがライトトレイルを抱く。",
        statement:
          "堀の見下ろし位置を事前にリサーチし、カーブの中心が画面に収まる角度で三脚を固定しました。1秒露光で光跡を滑らかに伸ばし、水面の反射を同時に残しています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-16.webp",
        alt: "皇居外苑のライトトレイル 2",
        width: 2560,
        height: 1707,
        contentLocation: "Imperial Palace Outer Garden, Tokyo, Japan",
        datePublished: "2025-02-28",
        caption: "欄干越しに日比谷通りの灯が走る。",
        statement:
          "欄干のデザインを活かすため、前ボケとして画面下に配置しました。車の列が整うまで数本見送り、露出を-0.5EVにして夜景の色を引き締めています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-17.webp",
        alt: "皇居外苑のライトトレイル 3",
        width: 2560,
        height: 1707,
        contentLocation: "Imperial Palace Outer Garden, Tokyo, Japan",
        datePublished: "2025-02-28",
        caption: "車列の軌跡が皇居の縁に沿う。",
        statement:
          "車道のカーブが最も美しく見える位置を探り、望遠で圧縮しました。信号サイクルを数え、光跡が途切れず繋がる1.3秒に設定しています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-18.webp",
        alt: "皇居外苑のライトトレイル 4",
        width: 2560,
        height: 1707,
        contentLocation: "Imperial Palace Outer Garden, Tokyo, Japan",
        datePublished: "2025-02-28",
        caption: "水面に反射したヘッドライトが揺れる。",
        statement:
          "風が止む瞬間を待ち、水面の揺れが最小になるタイミングで撮影しました。偏光を弱めて反射を残し、露出を-0.3EVに抑えて光の芯を守っています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-19.webp",
        alt: "九段下の朝霧とビル群",
        width: 1707,
        height: 2560,
        contentLocation: "Kudanshita, Tokyo, Japan",
        datePublished: "2025-02-28",
        caption: "朝霧が九段下のビルを霞ませる。",
        statement:
          "霧の濃さが刻々と変わるため、連続で露出を変えながら撮影しました。逆光で浮かぶ粒を捉えるため1/160秒に設定し、靄の柔らかさを残しています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-20.webp",
        alt: "九段下の朝霧とビル群 2",
        width: 1707,
        height: 2560,
        contentLocation: "Kudanshita, Tokyo, Japan",
        datePublished: "2025-02-28",
        caption: "霞の中で高層が輪郭を現す。",
        statement:
          "ビルの輪郭がわずかに見える濃さを狙い、露出を+0.3EVにして白く飛び過ぎないよう調整しました。縦構図で高さを誇張し、霧のレイヤーを引き出しています。",
      },
      {
        src: "/content/series/personal/elevated-citylines/elevated-citylines-21.webp",
        alt: "九段下の朝霧とビル群 3",
        width: 2560,
        height: 1707,
        contentLocation: "Kudanshita, Tokyo, Japan",
        datePublished: "2025-02-28",
        caption: "日差しが坂道の影を引き延ばす。",
        statement:
          "坂道の影が伸びる朝の時間帯に合わせ、ローアングルで影の線を強調しました。人の足取りが重ならないタイミングを待ち、都市の目覚めを一枚に凝縮しています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 35mm F1.4 GM" },
      { label: "Settings", value: "1/500s · F8 · ISO 320" },
    ],
    relatedCta: {
      heading: "展望ロケーション撮影のご相談",
      body: "三脚制限や入場制限がある施設での撮影も、時間帯調整や申請を含めてコーディネートします。",
      href: "/services",
      label: "Servicesを見る",
    },
  };
