import type { SeriesDetails } from '../types';

export const harborLanterns: SeriesDetails = {
    slug: "harbor-lanterns",
  published: false,
    category: "Personal",
    title: "Harbor Lanterns",
    year: 2024,
    location: "Yokohama & Tokyo",
    palette: "color",
    focus: "urban",
    synopsis: "港町と水辺に灯る明かりを集め、ブルーアワーからナイトまでの時間軸を綴ったシリーズ。",
    lead: "横浜の港エリアと豊洲のベイエリアを歩き、光が水面や街の装飾に溶ける瞬間を集めました。",
    story:
      "海風によるブレを抑えるため1/160s以上をキープしつつ、光の密度に合わせてNDフィルターで露出をコントロール。色温度は街灯の色に揃え、統一感を持たせています。",
    tags: ["Urban", "Night", "Waterfront"],
    cover: {
      src: "/content/series/personal/harbor-lanterns/harbor-lanterns-01.webp",
      alt: "横浜港に立ち並ぶクレーンと夜景",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/content/series/personal/harbor-lanterns/harbor-lanterns-02.webp",
      alt: "横浜港に立ち並ぶクレーンと夜景 2",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/content/series/personal/harbor-lanterns/harbor-lanterns-01.webp",
        alt: "横浜港に立ち並ぶクレーンと夜景",
        width: 2560,
        height: 1707,
        contentLocation: "Yokohama, Kanagawa, Japan",
        datePublished: "2024-11-12",
      },
      {
        src: "/content/series/personal/harbor-lanterns/harbor-lanterns-02.webp",
        alt: "横浜港に立ち並ぶクレーンと夜景 2",
        width: 2560,
        height: 1707,
        contentLocation: "Yokohama, Kanagawa, Japan",
        datePublished: "2024-11-12",
      },
      {
        src: "/content/series/personal/harbor-lanterns/harbor-lanterns-03.webp",
        alt: "横浜港に立ち並ぶクレーンと夜景 3",
        width: 2560,
        height: 1707,
        contentLocation: "Yokohama, Kanagawa, Japan",
        datePublished: "2024-11-12",
      },
      {
        src: "/content/series/personal/harbor-lanterns/harbor-lanterns-04.webp",
        alt: "横浜港のブルーアワー",
        width: 2560,
        height: 1707,
        contentLocation: "Yokohama, Kanagawa, Japan",
        datePublished: "2024-11-12",
      },
      {
        src: "/content/series/personal/harbor-lanterns/harbor-lanterns-05.webp",
        alt: "横浜中華街のランタン",
        width: 2048,
        height: 2560,
        contentLocation: "Yokohama Chinatown, Kanagawa, Japan",
        datePublished: "2024-11-12",
      },
      {
        src: "/content/series/personal/harbor-lanterns/harbor-lanterns-06.webp",
        alt: "横浜中華街のランタン 2",
        width: 2048,
        height: 2560,
        contentLocation: "Yokohama Chinatown, Kanagawa, Japan",
        datePublished: "2024-11-12",
      },
      {
        src: "/content/series/personal/harbor-lanterns/harbor-lanterns-07.webp",
        alt: "横浜中華街のランタン 3",
        width: 1707,
        height: 2560,
        contentLocation: "Yokohama Chinatown, Kanagawa, Japan",
        datePublished: "2024-11-12",
      },
      {
        src: "/content/series/personal/harbor-lanterns/harbor-lanterns-08.webp",
        alt: "横浜中華街のランタン 4",
        width: 1707,
        height: 2560,
        contentLocation: "Yokohama Chinatown, Kanagawa, Japan",
        datePublished: "2024-11-12",
      },
      {
        src: "/content/series/personal/harbor-lanterns/harbor-lanterns-09.webp",
        alt: "豊洲の水辺に映るライト",
        width: 2560,
        height: 1707,
        contentLocation: "Toyosu, Tokyo, Japan",
        datePublished: "2024-12-08",
      },
      {
        src: "/content/series/personal/harbor-lanterns/harbor-lanterns-10.webp",
        alt: "豊洲の水辺に映るライト 2",
        width: 2560,
        height: 1707,
        contentLocation: "Toyosu, Tokyo, Japan",
        datePublished: "2024-12-08",
      },
      {
        src: "/content/series/personal/harbor-lanterns/harbor-lanterns-11.webp",
        alt: "豊洲の水辺に映るライト 3",
        width: 2560,
        height: 1707,
        contentLocation: "Toyosu, Tokyo, Japan",
        datePublished: "2024-12-08",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 35mm F1.4 GM" },
      { label: "Settings", value: "1/500s · F8 · ISO 320" },
    ],
    relatedCta: {
      heading: "ナイトシティ撮影のご相談",
      body: "港町や水辺での長時間露光が必要な案件では、潮汐と風速を考慮したロケーション設計をご提案します。",
      href: "/services",
      label: "Servicesを見る",
    },
  };
