import type { SeriesDetails } from '../types';

export const historicDistricts: SeriesDetails = {
  slug: "historic-districts",
  published: true,
  category: "Personal",
  title: "Historic Districts",
  year: 2024,
  location: "Tokyo, Japan",
  palette: "color",
  focus: "urban",
  synopsis: "伝統と現代が交差する街。浅草、上野、九段など、東京の歴史的地区を巡るシリーズ。",
  lead: "東京の下町や歴史的地区を訪れ、伝統的な建築と現代の街が共存する風景を撮影しました。提灯の灯り、寺社の佇まい、商店街の賑わいなど、時代を超えて受け継がれる東京の表情を記録しています。",
  story: "浅草、上野、九段、谷中など、江戸の面影を残す地域を中心に撮影。観光客で賑わう昼間だけでなく、早朝や夕暮れの静かな時間帯も狙い、地域が持つ本来の雰囲気を引き出すことを心がけました。",
  tags: ["Historic", "Traditional", "Urban", "Culture"],
  cover: {
    src: "/series-gallery/asakusa-promenade/asakusa-promenade-01.webp",
    alt: "浅草仲見世通りの賑わい",
    width: 2560,
    height: 1707,
  },
  heroImage: {
    src: "/series-gallery/asakusa-promenade/asakusa-promenade-01.webp",
    alt: "Historic Districts - 歴史的地区の表情",
    width: 2560,
    height: 1707,
  },
  gallery: [
    {
      src: "/series-gallery/asakusa-promenade/asakusa-promenade-01.webp",
      alt: "浅草仲見世通りの賑わい",
      width: 2560,
      height: 1707,
      contentLocation: "Asakusa, Tokyo, Japan",
      datePublished: "2024-05-20",
      caption: "仲見世通りが江戸の記憶を紡ぐ。",
    },
    {
      src: "/series-gallery/lantern-arcade/lantern-arcade-01.webp",
      alt: "提灯が灯るアーケード街",
      width: 1707,
      height: 2560,
      contentLocation: "Tokyo, Japan",
      datePublished: "2024-06-12",
      caption: "提灯の灯りが夕暮れを温かく照らす。",
    },
    {
      src: "/series-gallery/kudan-layers/kudan-layers-01.webp",
      alt: "九段の街並みと歴史的建築",
      width: 2560,
      height: 1707,
      contentLocation: "Kudan, Tokyo, Japan",
      datePublished: "2024-08-25",
      caption: "九段の層が歴史を積み重ねる。",
    },
    {
      src: "/series-gallery/ueno-arcadia/ueno-arcadia-01.webp",
      alt: "上野公園の緑と建築",
      width: 2560,
      height: 1707,
      contentLocation: "Ueno, Tokyo, Japan",
      datePublished: "2024-09-15",
      caption: "上野の緑が都市の記憶を守る。",
    },
  ],
  exif: [
    { label: "Camera", value: "Sony α7 III (ILCE-7M3)" },
    { label: "Lens", value: "FE 24-70mm F2.8 GM / FE 85mm F1.4" },
    { label: "Settings", value: "1/125s - 1/500s · F2.8 - F8 · ISO 200-1600" },
  ],
  relatedCta: {
    heading: "文化・観光撮影のご依頼",
    body: "観光プロモーションや文化施設の記録撮影を承ります。",
    href: "/services",
    label: "Servicesを見る",
  },
};
