import type { SeriesDetails } from '../types';

export const lanternArcade: SeriesDetails = {
    slug: "lantern-arcade",
  published: false,
    category: "Personal",
    title: "Lantern Arcade",
    year: 2024,
    location: "Asakusa & Ginza",
    palette: "color",
    focus: "urban",
    synopsis: "浅草や銀座のアーケードを巡り、灯りと人のリズムが交わる瞬間を収集したシリーズ。",
    lead: "浅草の仲見世から銀座の街角まで、歩きながら連なる灯りと影を追い、都市の夜を彩るディテールに焦点を当てました。",
    story:
      "望遠で圧縮した灯籠の重なりと広角で捉えた路地の広がりを組み合わせ、F1.8前後の開放で光のにじみを活かしています。人流を邪魔しない位置から三脚レスで撮影し、シャッタースピードは1/200sを維持しました。",
    tags: ["Urban", "Night", "Street"],
    cover: {
      src: "/content/series/personal/lantern-arcade/lantern-arcade-01.webp",
      alt: "浅草の仲見世に連なるランタン",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/content/series/personal/lantern-arcade/lantern-arcade-02.webp",
      alt: "浅草の仲見世に連なるランタン 2",
      width: 1707,
      height: 2560,
    },
    gallery: [
      {
        src: "/content/series/personal/lantern-arcade/lantern-arcade-01.webp",
        alt: "浅草の仲見世に連なるランタン",
        width: 2560,
        height: 1707,
        contentLocation: "Asakusa, Tokyo, Japan",
        datePublished: "2024-08-22",
      },
      {
        src: "/content/series/personal/lantern-arcade/lantern-arcade-02.webp",
        alt: "浅草の仲見世に連なるランタン 2",
        width: 1707,
        height: 2560,
        contentLocation: "Asakusa, Tokyo, Japan",
        datePublished: "2024-08-22",
      },
      {
        src: "/content/series/personal/lantern-arcade/lantern-arcade-03.webp",
        alt: "浅草の仲見世に連なるランタン 3",
        width: 2560,
        height: 1707,
        contentLocation: "Asakusa, Tokyo, Japan",
        datePublished: "2024-08-22",
      },
      {
        src: "/content/series/personal/lantern-arcade/lantern-arcade-04.webp",
        alt: "浅草の仲見世に連なるランタン 4",
        width: 2560,
        height: 1707,
        contentLocation: "Asakusa, Tokyo, Japan",
        datePublished: "2024-08-22",
      },
      {
        src: "/content/series/personal/lantern-arcade/lantern-arcade-05.webp",
        alt: "浅草の仲見世に連なるランタン 5",
        width: 2560,
        height: 1707,
        contentLocation: "Asakusa, Tokyo, Japan",
        datePublished: "2024-08-22",
      },
      {
        src: "/content/series/personal/lantern-arcade/lantern-arcade-06.webp",
        alt: "銀座の夜を照らすライト",
        width: 1707,
        height: 2560,
        contentLocation: "Ginza, Tokyo, Japan",
        datePublished: "2024-11-21",
      },
      {
        src: "/content/series/personal/lantern-arcade/lantern-arcade-07.webp",
        alt: "銀座の夜を照らすライト 2",
        width: 1707,
        height: 2560,
        contentLocation: "Ginza, Tokyo, Japan",
        datePublished: "2024-11-21",
      },
      {
        src: "/content/series/personal/lantern-arcade/lantern-arcade-08.webp",
        alt: "銀座の夜を照らすライト 3",
        width: 2560,
        height: 1707,
        contentLocation: "Ginza, Tokyo, Japan",
        datePublished: "2024-11-21",
      },
      {
        src: "/content/series/personal/lantern-arcade/lantern-arcade-09.webp",
        alt: "銀座の夜を照らすライト 4",
        width: 2560,
        height: 1707,
        contentLocation: "Ginza, Tokyo, Japan",
        datePublished: "2024-11-21",
      },
      {
        src: "/content/series/personal/lantern-arcade/lantern-arcade-10.webp",
        alt: "銀座の夜を照らすライト 5",
        width: 2560,
        height: 1707,
        contentLocation: "Ginza, Tokyo, Japan",
        datePublished: "2024-11-21",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 III (ILCE-7M3)" },
      { label: "Lens", value: "FE 85mm F1.8" },
      { label: "Settings", value: "1/500s · F2 · ISO 800" },
    ],
    relatedCta: {
      heading: "商店街・ナイトロケのご相談",
      body: "観光地のアーケード撮影では混雑時間帯の調整や、許諾が必要な場合の窓口整理までサポートします。",
      href: "/services",
      label: "Servicesを見る",
    },
  };
