import type { SeriesDetails } from '../types';

export const springSanctuaries: SeriesDetails = {
    slug: "spring-sanctuaries",
  published: false,
    category: "Personal",
    title: "Spring Sanctuaries",
    year: 2025,
    location: "Tokyo & Yokohama",
    palette: "color",
    focus: "nature",
    synopsis: "都市に点在する公園と庭園を巡り、春先の湿度と光を収めたアーバンネイチャー。",
    lead: "東京から横浜までの公園や庭園を移動しながら、桜や新緑が街の空気と混ざり合う瞬間を収集しました。",
    story:
      "開園時間と天候をこまめにチェックし、柔らかい曇天や朝の逆光を狙って撮影。望遠で圧縮した枝ぶりと広角で捉えた水辺を組み合わせ、都市と自然の密度を再構成しています。",
    tags: ["Seasonal", "Garden", "Nature"],
    cover: {
      src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-01.webp",
      alt: "都心を彩る桜のアーチ",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-02.webp",
      alt: "都心を彩る桜のアーチ 2",
      width: 1707,
      height: 2560,
    },
    gallery: [
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-01.webp",
        alt: "都心を彩る桜のアーチ",
        width: 2560,
        height: 1707,
        contentLocation: "Tokyo, Japan",
        datePublished: "2025-03-28",
        caption: "水面の桜が街の色を映し返す。",
        statement:
          "ボートが動き出す前の静けさを狙い、ハーフNDで空の輝度を抑えて水面の反射を整えました。風が止む一拍を待ってシャッターを切り、街のライトと花の色調を揃えています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-02.webp",
        alt: "都心を彩る桜のアーチ 2",
        width: 1707,
        height: 2560,
        contentLocation: "Tokyo, Japan",
        datePublished: "2025-03-28",
        caption: "見上げた空が花の膜で覆われる。",
        statement:
          "縦構図でトンネルの奥行きを作り、枝の重なりが詰まり過ぎない位置まで後退しました。舞い落ちる花弁が流れないよう1/250秒で切り取り、空の青を少し残しています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-03.webp",
        alt: "都心を彩る桜のアーチ 3",
        width: 2560,
        height: 1707,
        contentLocation: "Tokyo, Japan",
        datePublished: "2025-03-28",
        caption: "遊歩道の桜が淡いアーチを描く。",
        statement:
          "歩道のカーブが最も綺麗に見える角度を探り、ローアングルで枝ぶりを強調しました。露出を-0.3EVに抑え、花の密度と手前のリズムが読み取れるようにしています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-04.webp",
        alt: "都心を彩る桜のアーチ 4",
        width: 1707,
        height: 2560,
        contentLocation: "Tokyo, Japan",
        datePublished: "2025-03-28",
        caption: "枝ぶりが春のリズムを空に刻む。",
        statement:
          "強い日差しで白飛びしやすかったため、露出を抑えて枝のラインを先に決めました。空の彩度を少し落とし、桜の淡いトーンが浮き上がるよう微調整しています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-05.webp",
        alt: "井の頭恩賜公園の池と木漏れ日",
        width: 2560,
        height: 1707,
        contentLocation: "Inokashira Park, Tokyo, Japan",
        datePublished: "2025-04-05",
        caption: "池の光が桜色をゆらめかせる。",
        statement:
          "偏光フィルターを半分だけ効かせ、反射と水中の色を同時に残しました。ボートの波紋が収まるタイミングを待ち、シャッターを1/30秒まで落として柔らかな揺らぎを描いています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-06.webp",
        alt: "井の頭恩賜公園の池と木漏れ日 2",
        width: 2560,
        height: 1707,
        contentLocation: "Inokashira Park, Tokyo, Japan",
        datePublished: "2025-04-05",
        caption: "水面に落ちる花弁が波紋を描く。",
        statement:
          "花弁の降り方を観察し、風が弱まる瞬間にシャッターを切りました。露出をわずかにアンダーにしてハイライトを守り、波紋の陰影を丁寧に残しています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-07.webp",
        alt: "井の頭恩賜公園の池と木漏れ日 3",
        width: 2560,
        height: 1707,
        contentLocation: "Inokashira Park, Tokyo, Japan",
        datePublished: "2025-04-05",
        caption: "木漏れ日と新緑が湿度を映す。",
        statement:
          "レンズヒーターで曇りを防ぎながら、逆光で透ける葉を狙いました。F4で奥のボケを保ち、湿度を感じるコントラストに抑えています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-08.webp",
        alt: "井の頭恩賜公園の池と木漏れ日 4",
        width: 2560,
        height: 1707,
        contentLocation: "Inokashira Park, Tokyo, Japan",
        datePublished: "2025-04-05",
        caption: "静かな水辺に枝影が重なる。",
        statement:
          "池面の黒が重くならないよう露出を微妙に上げ、シャドウを残しました。枝の配置を整えるため数歩ずつ位置を変え、重なり過ぎない瞬間を選んでいます。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-09.webp",
        alt: "上野恩賜公園の散策路",
        width: 1707,
        height: 2560,
        contentLocation: "Ueno Park, Tokyo, Japan",
        datePublished: "2025-03-30",
        caption: "上野の散策路に柔らかな朝霧が漂う。",
        statement:
          "霧が薄くなる直前を狙い、シャッター速度を1/100秒に落として空気の質感を拾いました。石畳の連なりが奥へ伸びるよう、画面端の垂直を丁寧に合わせています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-10.webp",
        alt: "上野恩賜公園の散策路 2",
        width: 2560,
        height: 1707,
        contentLocation: "Ueno Park, Tokyo, Japan",
        datePublished: "2025-03-30",
        caption: "レンガの手すりが春の気配を導く。",
        statement:
          "手すりのリズムを活かすために斜めから構え、前景を少しぼかして奥行きを出しました。人物の影が入らないタイミングを待ち、露出を-0.3EVに抑えています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-11.webp",
        alt: "上野恩賜公園の散策路 3",
        width: 2560,
        height: 1707,
        contentLocation: "Ueno Park, Tokyo, Japan",
        datePublished: "2025-03-30",
        caption: "小径の先で桜の影が重なり合う。",
        statement:
          "フォーカスピーキングで手前の桜を合わせ、奥の光が滲むよう開放寄りで撮影しました。背景の看板が目立たない角度を探り、画面全体のトーンを揃えています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-12.webp",
        alt: "上野動物園の朝の光",
        width: 2560,
        height: 1707,
        contentLocation: "Ueno Zoo, Tokyo, Japan",
        datePublished: "2025-03-30",
        caption: "温室の光が湿度を柔らかく散らす。",
        statement:
          "温室内の高湿度でレンズが曇るため、ドライクロスでこまめに拭きながら撮影しました。曇ったガラス越しの光を活かすため、露出をややプラスに振っています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-13.webp",
        alt: "上野動物園の朝の光 2",
        width: 2560,
        height: 1707,
        contentLocation: "Ueno Zoo, Tokyo, Japan",
        datePublished: "2025-03-30",
        caption: "ガラス越しの呼気が朝陽に滲む。",
        statement:
          "ガラス面の水滴が映る角度を探し、奥のハイライトが飛び過ぎないよう露出を調整しました。手前のボケを厚くすることで湿度のレイヤーを強調しています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-14.webp",
        alt: "三溪園の池と古建築",
        width: 2560,
        height: 1707,
        contentLocation: "Sankeien Garden, Yokohama, Japan",
        datePublished: "2024-11-08",
        caption: "三溪園の池が古建築を静止画に写す。",
        statement:
          "池面が静かになる風待ちをしながら、偏光を弱めて反射を残しました。建物の輪郭が沈まないよう、わずかにシャドウを持ち上げています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-15.webp",
        alt: "三溪園の池と古建築 2",
        width: 2560,
        height: 1707,
        contentLocation: "Sankeien Garden, Yokohama, Japan",
        datePublished: "2024-11-08",
        caption: "枝垂れ桜が屋根に寄り添う。",
        statement:
          "望遠で圧縮し、屋根瓦と花の距離感を詰めました。枝がフレームアウトしない位置を探り、わずかな揺れを抑えるため1/200秒に設定しています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-16.webp",
        alt: "三溪園の池と古建築 3",
        width: 2560,
        height: 1707,
        contentLocation: "Sankeien Garden, Yokohama, Japan",
        datePublished: "2024-11-08",
        caption: "灯籠と池が春宵を映し出す。",
        statement:
          "ライトアップの色が飽和しないよう露出を-1EVに落とし、水面の反射を優先しました。灯籠の位置関係を整えるため、数センチ単位で三脚を移動しています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-17.webp",
        alt: "靖国神社参道の桜",
        width: 2048,
        height: 2560,
        contentLocation: "Yasukuni Shrine, Tokyo, Japan",
        datePublished: "2025-04-12",
        caption: "靖国の参道に桜色のトンネルが生まれる。",
        statement:
          "参道を歩く人が途切れる時間帯を狙い、ハイライトが飛ばないよう露出を抑えました。鳥居の柱が歪まないよう中央に立ち、水平を慎重に合わせています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-18.webp",
        alt: "靖国神社参道の桜 2",
        width: 2048,
        height: 2560,
        contentLocation: "Yasukuni Shrine, Tokyo, Japan",
        datePublished: "2025-04-12",
        caption: "石鳥居と花の淡い呼吸が重なる。",
        statement:
          "鳥居と花房のバランスを取るため、ステップを上下して最適な高さを探りました。彩度を少し落として石の質感を残し、花の柔らかさを浮かび上がらせています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-19.webp",
        alt: "新宿御苑の冬枯れと緑",
        width: 1707,
        height: 2560,
        contentLocation: "Shinjuku Gyoen, Tokyo, Japan",
        datePublished: "2024-12-18",
        caption: "冬枯れの芝が早春の光を受け止める。",
        statement:
          "光が芝に斜めに入る時間を待ち、影のグラデーションを強調しました。望遠で圧縮し、常緑との対比が伝わるよう被写界深度を浅く保っています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-20.webp",
        alt: "新宿御苑の冬枯れと緑 2",
        width: 1707,
        height: 2560,
        contentLocation: "Shinjuku Gyoen, Tokyo, Japan",
        datePublished: "2024-12-18",
        caption: "池の縁に常緑と枯色が並ぶ。",
        statement:
          "色のコントラストを際立たせるためホワイトバランスを少し暖め、露出を-0.3EVに設定しました。水面の反射が主題を邪魔しないよう、角度を微調整しています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-21.webp",
        alt: "新宿御苑の冬枯れと緑 3",
        width: 2560,
        height: 1707,
        contentLocation: "Shinjuku Gyoen, Tokyo, Japan",
        datePublished: "2024-12-18",
        caption: "雪解けの芝目が柔らかい影を描く。",
        statement:
          "低い位置から芝のテクスチャを拾い、ハイライトが飛ばないようヒストグラムを確認しながら撮影しました。影の線が斜めに走る構図で、季節の移り変わりを表現しています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-22.webp",
        alt: "駒沢公園の並木",
        width: 2560,
        height: 1707,
        contentLocation: "Komazawa Park, Tokyo, Japan",
        datePublished: "2024-12-10",
        caption: "駒沢の並木が夕方の風を抱き留める。",
        statement:
          "夕暮れの暖色が並木を照らすタイミングを狙い、シャッターを1/125秒にして葉の揺れを残しました。歩道の白線が邪魔にならないよう、立ち位置を細かく調整しています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-23.webp",
        alt: "駒沢公園の並木 2",
        width: 2560,
        height: 1707,
        contentLocation: "Komazawa Park, Tokyo, Japan",
        datePublished: "2024-12-10",
        caption: "ランナーの視線を導く並木のアーチ。",
        statement:
          "ランナーの流れを観察し、人物が自然に入るまで待ちました。望遠で圧縮してアーチの密度を高め、被写界深度を浅くすることで視線を奥へ誘導しています。",
      },
      {
        src: "/content/series/personal/spring-sanctuaries/spring-sanctuaries-24.webp",
        alt: "駒沢公園の並木 3",
        width: 2560,
        height: 1707,
        contentLocation: "Komazawa Park, Tokyo, Japan",
        datePublished: "2024-12-10",
        caption: "トラック沿いの木々が夕暮れの粒を散らす。",
        statement:
          "トラックのカーブが美しく見える角度を探り、露出を-0.5EVにして木漏れ日の粒を浮かせました。背景のビルが目立たないよう、低めの視点で切り取っています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 70-200mm F2.8 GM II" },
      { label: "Settings", value: "1/320s · F4 · ISO 400" },
    ],
    relatedCta: {
      heading: "撮影のご相談はこちら",
      body: "シリーズに合わせたロケーション提案やスケジュール設計から撮影・納品まで一貫して対応します。",
      href: "/services",
      label: "Servicesを見る",
    },
  };
