import type { SeriesDetails } from '../types';

export const tokyoNightChronicles: SeriesDetails = {
  slug: "tokyo-night-chronicles",
  published: true,
  category: "Personal",
  title: "Tokyo Night Chronicles",
  year: 2025,
  location: "Tokyo, Japan",
  palette: "color",
  focus: "urban",
  synopsis: "東京の夜を彩る光の軌跡。都市の呼吸を長秒露光で切り取った夜景シリーズ。",
  lead: "夜の都心を縦横に走る光の軌跡を追い、ビルの呼吸と人のリズムをひとつのフレームに束ねたシリーズ。長秒露光と多重露光で、東京の夜が持つ独特のエネルギーを表現しました。",
  story: "新宿、渋谷、銀座、皇居外苑など、東京を代表する夜景スポットを巡り、手持ちと三脚を使い分けながら撮影。街灯ごとの色温度を丁寧に整え、車のヘッドライトが描く光跡が街の呼吸になるよう、信号のサイクルを計算しながらシャッターを切りました。ネオンの輝きと都市の静けさが共存する瞬間を捉えています。",
  tags: ["Urban", "Night", "Long Exposure", "Cityscape"],
  cover: {
    src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-01.webp",
    alt: "夜の新宿高層ビル群と交差するヘッドライトの軌跡",
    width: 2560,
    height: 1707,
  },
  heroImage: {
    src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-01.webp",
    alt: "Tokyo Night Chronicles - 新宿の夜景と光跡",
    width: 2560,
    height: 1707,
  },
  gallery: [
    {
      src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-01.webp",
      alt: "夜の新宿高層ビル群と交差するヘッドライトの軌跡",
      width: 2560,
      height: 1707,
      contentLocation: "Shinjuku, Tokyo, Japan",
      datePublished: "2024-10-15",
      caption: "高層の壁が夜気を吸い込み、車の光が呼吸に変わる。",
      statement: "新宿の歩道橋から粘り、風に揺れる標識を避けるために三脚の脚を低く構えました。光跡が街の呼吸になるよう信号のサイクルをメモしながらタイミングを合わせています。",
    },
    {
      src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-02.webp",
      alt: "歌舞伎町方面を見下ろす都市の光のレイヤー",
      width: 2560,
      height: 1707,
      contentLocation: "Shinjuku, Tokyo, Japan",
      datePublished: "2024-10-17",
      caption: "雑踏のざわめきが光の層に溶けていく。",
      statement: "歌舞伎町の早朝、まだ飲み屋の灯りが残る時間帯を狙いました。ネオンの色が流れすぎないよう、露光を短めに切り上げ人的なリズムを残しています。",
    },
    {
      src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-04.webp",
      alt: "俯瞰で捉えた渋谷スクランブル交差点の光跡",
      width: 1710,
      height: 2560,
      contentLocation: "Shibuya, Tokyo, Japan",
      datePublished: "2025-08-05",
      caption: "スクランブルの渦を俯瞰の静けさで包み込む。",
      statement: "渋谷の屋上から撮影し、雨上がりで路面が反射するタイミングを待ちました。人の流れが重なりすぎないよう、複数露光を重ねてパターンを整えています。",
    },
    {
      src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-05.webp",
      alt: "渋谷の街路に浮かぶネオンと歩行者のシルエット",
      width: 1710,
      height: 2560,
      contentLocation: "Shibuya, Tokyo, Japan",
      datePublished: "2025-08-05",
      caption: "歩行者の気配とネオンの余韻を同じ距離で。",
      statement: "路地の奥で息を潜めながら、人物の歩幅と光の揺らぎが揃う瞬間を狙いました。ISOを抑え暗部のざらつきを残すことで街の湿度を出しています。",
    },
    {
      src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-06.webp",
      alt: "銀座中央通りを照らすショーウィンドウの光",
      width: 1707,
      height: 2560,
      contentLocation: "Ginza, Tokyo, Japan",
      datePublished: "2025-06-14",
      caption: "ショーウィンドウの冷たい光が銀座を染める。",
      statement: "ショーウィンドウの照度が揃うタイミングを待ち、色温度を手動で合わせています。道路の反射が滑らかに繋がるよう、横断歩道が空く瞬間にシャッターを切りました。",
    },
    {
      src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-07.webp",
      alt: "銀座の夜景と車列が描く柔らかな光",
      width: 2048,
      height: 2560,
      contentLocation: "Ginza, Tokyo, Japan",
      datePublished: "2025-06-14",
      caption: "車列のレガートが街路樹をやわらかく照らす。",
      statement: "少し離れた歩道橋から俯瞰し、望遠で圧縮をかけました。ヘッドライトの光量差が激しいため複数露光をコンポジットして柔らかいグラデーションに整えています。",
    },
    {
      src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-08.webp",
      alt: "皇居外苑の並木越しに望む都心の夜空",
      width: 1707,
      height: 2560,
      contentLocation: "Imperial Palace, Tokyo, Japan",
      datePublished: "2025-02-28",
      caption: "皇居の闇と都心の灯りが同じ呼吸をする。",
      statement: "皇居外苑の静けさを崩さないよう、遠くから長秒露光で撮影。木々が風で揺れない合間に撮り、空の階調を残すためハイライトを抑えめにしました。",
    },
    {
      src: "/series-gallery/elevated-citylines/elevated-citylines-01.webp",
      alt: "高架から見下ろす東京の夜景パノラマ",
      width: 2560,
      height: 1707,
      contentLocation: "Tokyo, Japan",
      datePublished: "2024-11-20",
      caption: "高架の視点から都市全体のリズムを俯瞰する。",
    },
    {
      src: "/series-gallery/neon-cascades/neon-cascades-01.webp",
      alt: "ネオンの滝のように連なる看板と街路",
      width: 1707,
      height: 2560,
      contentLocation: "Shinjuku, Tokyo, Japan",
      datePublished: "2024-09-10",
      caption: "ネオンの滝が街を染め上げる。",
    },
  ],
  exif: [
    { label: "Camera", value: "Sony α7 III (ILCE-7M3)" },
    { label: "Lens", value: "FE 24-70mm F2.8 GM / FE 50mm F1.4" },
    { label: "Settings", value: "1/50s - 8s · F1.4 - F8 · ISO 400-1600" },
    { label: "Technique", value: "Long Exposure, Multiple Exposure" },
  ],
  relatedCta: {
    heading: "ナイトシティ撮影のご依頼",
    body: "広告や自治体プロモーション向けに、ロケハンから長時間露光の演出まで一括でプランニングします。",
    href: "/services",
    label: "Servicesを見る",
  },
};
