import type { SeriesDetails } from '../types';

export const waterfrontMoments: SeriesDetails = {
  slug: "waterfront-moments",
  published: true,
  category: "Personal",
  title: "Waterfront Moments",
  year: 2024,
  location: "Tokyo, Japan",
  palette: "color",
  focus: "urban",
  synopsis: "東京の水辺が見せる表情。運河、港、海沿いに広がる静かな時間を切り取ったシリーズ。",
  lead: "東京湾岸エリアや隅田川周辺の運河を巡り、水面に映る光と街の表情を捉えました。夕暮れから夜にかけての青い時間帯を中心に、水と都市が織りなす静謐な風景を記録しています。",
  story: "豊洲、晴海、お台場、月島など、東京の水辺を代表するロケーションで撮影。潮の満ち引きや風の強さを確認しながら、水面の反射が最も美しくなるタイミングを待ちました。ブルーアワーの柔らかな光が水面に溶け込む瞬間を大切にしています。",
  tags: ["Waterfront", "Blue Hour", "Urban", "Reflection"],
  cover: {
    src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-01.webp",
    alt: "ブルーアワーの港に浮かぶ船と都市の明かり",
    width: 2560,
    height: 1707,
  },
  heroImage: {
    src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-01.webp",
    alt: "Waterfront Moments - 東京湾岸のブルーアワー",
    width: 2560,
    height: 1707,
  },
  gallery: [
    {
      src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-01.webp",
      alt: "ブルーアワーの港に浮かぶ船と都市の明かり",
      width: 2560,
      height: 1707,
      contentLocation: "Tokyo Bay, Japan",
      datePublished: "2024-07-22",
      caption: "ブルーアワーが港を青く染め、船が静かに呼吸する。",
    },
    {
      src: "/series-gallery/canal-afterglow/canal-afterglow-01.webp",
      alt: "夕暮れの運河に映る街の灯り",
      width: 2560,
      height: 1707,
      contentLocation: "Tsukishima, Tokyo, Japan",
      datePublished: "2024-08-15",
      caption: "運河の水面が夕焼けの残光を映し出す。",
    },
    {
      src: "/series-gallery/canal-ribbons/canal-ribbons-01.webp",
      alt: "運河を縫うように走る光のリボン",
      width: 2560,
      height: 1707,
      contentLocation: "Toyosu, Tokyo, Japan",
      datePublished: "2024-09-05",
      caption: "水面に描かれる光のリボンが都市のリズムを奏でる。",
    },
    {
      src: "/series-gallery/harbor-lanterns/harbor-lanterns-01.webp",
      alt: "港の提灯が灯る夜景",
      width: 1707,
      height: 2560,
      contentLocation: "Odaiba, Tokyo, Japan",
      datePublished: "2024-06-18",
      caption: "港の提灯が水面に揺れる。",
    },
    {
      src: "/series-gallery/first-light-voyage/first-light-voyage-01.webp",
      alt: "朝焼けの東京湾を航行する船",
      width: 2560,
      height: 1707,
      contentLocation: "Tokyo Bay, Japan",
      datePublished: "2024-05-10",
      caption: "夜明けの海が新しい一日を迎える。",
    },
  ],
  exif: [
    { label: "Camera", value: "Sony α7 III (ILCE-7M3)" },
    { label: "Lens", value: "FE 24-70mm F2.8 GM" },
    { label: "Settings", value: "1/125s - 2s · F4 - F8 · ISO 400-800" },
  ],
  relatedCta: {
    heading: "水辺の風景撮影のご相談",
    body: "不動産プロモーションや観光ガイド向けに、水辺のロケーション撮影を承ります。",
    href: "/contact",
    label: "Contact Me",
  },
};
