import { unusedSeriesDetails } from "./series-unused";

export type WorkTag =
  | "urban"
  | "nature"
  | "motion"
  | "people"
  | "monochrome"
  | "color";

export type SeriesImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  contentLocation: string;
  datePublished: string;
  caption?: string;
  statement?: string;
};

export type SeriesDetails = {
  slug: string;
  title: string;
  year: number;
  location: string;
  palette: WorkTag;
  focus: WorkTag;
  /** EN-led 併記の英語シノプシス（暫定・JA と対。CEO 実コピー確定時に統合） */
  synopsisEn?: string;
  synopsis: string;
  lead: string;
  story: string;
  tags: string[];
  cover: {
    src: string;
    alt: string;
    width: number;
    height: number;
  };
  heroImage: {
    src: string;
    alt: string;
    width: number;
    height: number;
  };
  gallery: SeriesImage[];
  exif: Array<{ label: string; value: string }>;
  relatedCta: {
    heading: string;
    body: string;
    href: string;
    label: string;
  };
};

const baseSeriesDetails: SeriesDetails[] = [
  {
    slug: "tokyo-night-lines",
    title: "Tokyo Night Lines",
    year: 2025,
    location: "新宿 · 渋谷 · 銀座",
    palette: "color",
    focus: "urban",
    synopsisEn: "Layers of light in motion — a nightscape series following the city as it breathes.",
    synopsis: "夜を走る光をレイヤーにし、都心が呼吸する瞬間を追った夜景シリーズ。",
    lead: "夜の都心を縫う光の軌跡を追い、ビルの呼吸と人のリズムをひとつのレイヤーに束ねたシリーズ。",
    story:
      "手持ちと三脚を使い分けながら長秒露光と多重露光を重ね、街灯ごとの色温度を整えて都市のリズムを描き出しました。",
    tags: ["Urban", "Night", "Long Exposure"],
    cover: {
      src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-01.webp",
      alt: "夜の新宿高層ビル群と交差するヘッドライトの軌跡",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-01.webp",
      alt: "夜の新宿高層ビル群と交差するヘッドライトの軌跡",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-01.webp",
        alt: "夜の新宿高層ビル群と交差するヘッドライトの軌跡",
        width: 2560,
        height: 1707,
        contentLocation: "新宿",
        datePublished: "2024-10-15",
        caption: "高層の壁が夜気を吸い込み、車の光が呼吸に変わる。",
        statement:
          "新宿の歩道橋から粘り、風に揺れる標識を避けるために三脚の脚を低く構えました。光跡が街の呼吸になるよう信号のサイクルをメモしながらタイミングを合わせています。",
      },
      {
        src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-02.webp",
        alt: "歌舞伎町方面を見下ろす都市の光のレイヤー",
        width: 2560,
        height: 1707,
        contentLocation: "新宿",
        datePublished: "2024-10-17",
        caption: "雑踏のざわめきが光の層に溶けていく。",
        statement:
          "歌舞伎町の早朝、まだ飲み屋の灯りが残る時間帯を狙いました。ネオンの色が流れすぎないよう、露光を短めに切り上げ人的なリズムを残しています。",
      },
      {
        src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-03.webp",
        alt: "縦構図で切り取った新宿のタワーとネオンのライン",
        width: 1707,
        height: 2560,
        contentLocation: "新宿",
        datePublished: "2024-10-17",
        caption: "縦のリズムで街を刻むネオンの柱。",
        statement:
          "縦構図で都市の密度を強調するため、手持ちで複数ショットを撮影し最も滑らかな光のラインを選びました。奥行きを保つために前ボケを控えめにしています。",
      },
      {
        src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-04.webp",
        alt: "俯瞰で捉えた渋谷スクランブル交差点の光跡",
        width: 1710,
        height: 2560,
        contentLocation: "渋谷",
        datePublished: "2025-08-05",
        caption: "スクランブルの渦を俯瞰の静けさで包み込む。",
        statement:
          "渋谷の屋上から撮影し、雨上がりで路面が反射するタイミングを待ちました。人の流れが重なりすぎないよう、複数露光を重ねてパターンを整えています。",
      },
      {
        src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-05.webp",
        alt: "渋谷の街路に浮かぶネオンと歩行者のシルエット",
        width: 1710,
        height: 2560,
        contentLocation: "渋谷",
        datePublished: "2025-08-05",
        caption: "歩行者の気配とネオンの余韻を同じ距離で。",
        statement:
          "路地の奥で息を潜めながら、人物の歩幅と光の揺らぎが揃う瞬間を狙いました。ISOを抑え暗部のざらつきを残すことで街の湿度を出しています。",
      },
      {
        src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-06.webp",
        alt: "銀座中央通りを照らすショーウィンドウの光",
        width: 1707,
        height: 2560,
        contentLocation: "銀座",
        datePublished: "2025-06-14",
        caption: "ショーウィンドウの冷たい光が銀座を染める。",
        statement:
          "ショーウィンドウの照度が揃うタイミングを待ち、色温度を手動で合わせています。道路の反射が滑らかに繋がるよう、横断歩道が空く瞬間にシャッターを切りました。",
      },
      {
        src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-07.webp",
        alt: "銀座の夜景と車列が描く柔らかな光",
        width: 2048,
        height: 2560,
        contentLocation: "銀座",
        datePublished: "2025-06-14",
        caption: "車列のレガートが街路樹をやわらかく照らす。",
        statement:
          "少し離れた歩道橋から俯瞰し、望遠で圧縮をかけました。ヘッドライトの光量差が激しいため複数露光をコンポジットして柔らかいグラデーションに整えています。",
      },
      {
        src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-08.webp",
        alt: "皇居外苑の並木越しに望む都心の夜空",
        width: 1707,
        height: 2560,
        contentLocation: "大手町",
        datePublished: "2025-02-28",
        caption: "皇居の闇と都心の灯りが同じ呼吸をする。",
        statement:
          "皇居外苑の静けさを崩さないよう、遠くから長秒露光で撮影。木々が風で揺れない合間に撮り、空の階調を残すためハイライトを抑えめにしました。",
      },
      {
        src: "/series-gallery/tokyo-night-lines/tokyo-night-lines-09.webp",
        alt: "皇居外苑の周回路を沿う光跡とビルのアウトライン",
        width: 1707,
        height: 2560,
        contentLocation: "大手町",
        datePublished: "2025-02-28",
        caption: "周回路の光跡が夜のランナーを包み込む。",
        statement:
          "ランナーの軌跡を残すため、露光時間を変えながら複数回撮影しています。手前の街灯が強すぎるため、ハーフNDを使ってコントラストを整えました。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 III (ILCE-7M3)" },
      { label: "Lens", value: "50mm F1.4 DG HSM | Art 018" },
      { label: "Settings", value: "1/50s · F1.4 · ISO 800" },
    ],
    relatedCta: {
      heading: "ナイトシティ撮影のご相談はこちら",
      body: "広告や自治体プロモーション向けに、ロケハンから長時間露光の演出まで一括でプランニングします。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "neon-cascades",
    title: "Neon Cascades",
    year: 2024,
    location: "渋谷 · 表参道・渋谷",
    palette: "color",
    focus: "urban",
    synopsisEn: "Shibuya's slopes and crossings, caught in the moment neon pours down.",
    synopsis: "渋谷の坂と交差点を巡り、ネオンが降り注ぐ瞬間を切り取ったナイトシリーズ。",
    lead: "スクランブル交差点から宇田川町までを歩き、街の反射と人の流れが交わる瞬間を集中的に記録しました。",
    story:
      "雨上がりを狙って撮影し、路面の反射にネオンが映るタイミングで1/30s前後に設定。流し撮りと静止の対比で都市のリズムを演出しています。",
    tags: ["Urban", "Night", "Motion"],
    cover: {
      src: "/series-gallery/neon-cascades/neon-cascades-01.webp",
      alt: "渋谷スクランブル交差点の夜景",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/neon-cascades/neon-cascades-02.webp",
      alt: "渋谷スクランブル交差点の夜景 2",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/neon-cascades/neon-cascades-01.webp",
        alt: "渋谷スクランブル交差点の夜景",
        width: 2560,
        height: 1707,
        contentLocation: "渋谷",
        datePublished: "2024-09-07",
      },
      {
        src: "/series-gallery/neon-cascades/neon-cascades-02.webp",
        alt: "渋谷スクランブル交差点の夜景 2",
        width: 2560,
        height: 1707,
        contentLocation: "渋谷",
        datePublished: "2024-09-07",
      },
      {
        src: "/series-gallery/neon-cascades/neon-cascades-03.webp",
        alt: "渋谷スクランブル交差点の夜景 3",
        width: 2560,
        height: 1707,
        contentLocation: "表参道・渋谷",
        datePublished: "2024-10-28",
      },
      {
        src: "/series-gallery/neon-cascades/neon-cascades-04.webp",
        alt: "渋谷スクランブル交差点の夜景 4",
        width: 2560,
        height: 1707,
        contentLocation: "表参道・渋谷",
        datePublished: "2024-10-28",
      },
      {
        src: "/series-gallery/neon-cascades/neon-cascades-05.webp",
        alt: "渋谷スクランブル交差点の夜景 5",
        width: 2560,
        height: 1707,
        contentLocation: "表参道・渋谷",
        datePublished: "2024-10-28",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 24-70mm F2.8 GM II" },
      { label: "Settings", value: "1/20s · F6.3 · ISO 2500" },
    ],
    relatedCta: {
      heading: "ナイトスナップのご相談",
      body: "渋谷エリアの夜間撮影では人流制御や機材制限に合わせたプランニングをご案内します。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "lantern-arcade",
    title: "Lantern Arcade",
    year: 2024,
    location: "浅草 · 上野・浅草 · 銀座",
    palette: "color",
    focus: "urban",
    synopsisEn: "Arcades of Asakusa and Ginza, where lantern light meets the rhythm of the crowd.",
    synopsis: "浅草や銀座のアーケードを巡り、灯りと人のリズムが交わる瞬間を収集したシリーズ。",
    lead: "浅草の仲見世から銀座の街角まで、歩きながら連なる灯りと影を追い、都市の夜を彩るディテールに焦点を当てました。",
    story:
      "望遠で圧縮した灯籠の重なりと広角で捉えた路地の広がりを組み合わせ、F1.8前後の開放で光のにじみを活かしています。人流を邪魔しない位置から三脚レスで撮影し、シャッタースピードは1/200sを維持しました。",
    tags: ["Urban", "Night", "Street"],
    cover: {
      src: "/series-gallery/lantern-arcade/lantern-arcade-01.webp",
      alt: "浅草の仲見世に連なるランタン",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/lantern-arcade/lantern-arcade-02.webp",
      alt: "浅草の仲見世に連なるランタン 2",
      width: 1707,
      height: 2560,
    },
    gallery: [
      {
        src: "/series-gallery/lantern-arcade/lantern-arcade-01.webp",
        alt: "浅草の仲見世に連なるランタン",
        width: 2560,
        height: 1707,
        contentLocation: "浅草",
        datePublished: "2024-12-28",
      },
      {
        src: "/series-gallery/lantern-arcade/lantern-arcade-02.webp",
        alt: "浅草の仲見世に連なるランタン 2",
        width: 1707,
        height: 2560,
        contentLocation: "浅草",
        datePublished: "2024-12-28",
      },
      {
        src: "/series-gallery/lantern-arcade/lantern-arcade-03.webp",
        alt: "浅草の仲見世に連なるランタン 3",
        width: 2560,
        height: 1707,
        contentLocation: "浅草",
        datePublished: "2024-12-28",
      },
      {
        src: "/series-gallery/lantern-arcade/lantern-arcade-04.webp",
        alt: "浅草の仲見世に連なるランタン 4",
        width: 2560,
        height: 1707,
        contentLocation: "浅草",
        datePublished: "2024-12-28",
      },
      {
        src: "/series-gallery/lantern-arcade/lantern-arcade-05.webp",
        alt: "浅草の仲見世に連なるランタン 5",
        width: 2560,
        height: 1707,
        contentLocation: "上野・浅草",
        datePublished: "2024-12-18",
      },
      {
        src: "/series-gallery/lantern-arcade/lantern-arcade-06.webp",
        alt: "銀座の夜を照らすライト",
        width: 1707,
        height: 2560,
        contentLocation: "銀座",
        datePublished: "2025-06-14",
      },
      {
        src: "/series-gallery/lantern-arcade/lantern-arcade-07.webp",
        alt: "銀座の夜を照らすライト 2",
        width: 1707,
        height: 2560,
        contentLocation: "銀座",
        datePublished: "2025-06-14",
      },
      {
        src: "/series-gallery/lantern-arcade/lantern-arcade-08.webp",
        alt: "銀座の夜を照らすライト 3",
        width: 2560,
        height: 1707,
        contentLocation: "銀座",
        datePublished: "2025-06-14",
      },
      {
        src: "/series-gallery/lantern-arcade/lantern-arcade-09.webp",
        alt: "銀座の夜を照らすライト 4",
        width: 2560,
        height: 1707,
        contentLocation: "銀座",
        datePublished: "2025-06-14",
      },
      {
        src: "/series-gallery/lantern-arcade/lantern-arcade-10.webp",
        alt: "銀座の夜を照らすライト 5",
        width: 2560,
        height: 1707,
        contentLocation: "銀座",
        datePublished: "2025-06-14",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 III (ILCE-7M3)" },
      { label: "Lens", value: "FE 85mm F1.8" },
      { label: "Settings", value: "1/800s · F9 · ISO 2500" },
    ],
    relatedCta: {
      heading: "商店街・ナイトロケのご相談",
      body: "観光地のアーケード撮影では混雑時間帯の調整や、許諾が必要な場合の窓口整理までサポートします。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "canal-ribbons",
    title: "Canal Ribbons",
    year: 2025,
    location: "中目黒・代官山 · 代官山 · 目黒・品川",
    palette: "color",
    focus: "urban",
    synopsisEn: "Walking the canal from Nakameguro to Shinagawa, as dusk turns to night.",
    synopsis: "中目黒から品川へと続く運河沿いを歩き、夕景から夜景へ変わる瞬間を束ねたシリーズ。",
    lead: "代官山から中目黒、目黒川沿いの橋を渡りながら、街灯と車列が運河に描くリボンのような光跡を追いました。",
    story:
      "水面の反射を柔らかくするため偏光フィルターを調整しつつ、橋上では手すりを前ボケに入れて立体感を演出。夕暮れ時は1/60sまで落として人の流れを残し、夜は三脚不可の環境でもぶれないシャッタースピードを維持しました。",
    tags: ["Urban", "Night", "Waterfront"],
    cover: {
      src: "/series-gallery/canal-ribbons/canal-ribbons-01.webp",
      alt: "代官山から中目黒へ続くライトと運河",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/canal-ribbons/canal-ribbons-02.webp",
      alt: "代官山から中目黒へ続くライトと運河 2",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-01.webp",
        alt: "代官山から中目黒へ続くライトと運河",
        width: 2560,
        height: 1707,
        contentLocation: "中目黒・代官山",
        datePublished: "2024-09-13",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-02.webp",
        alt: "代官山から中目黒へ続くライトと運河 2",
        width: 2560,
        height: 1707,
        contentLocation: "中目黒・代官山",
        datePublished: "2024-09-13",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-03.webp",
        alt: "代官山から中目黒へ続くライトと運河 3",
        width: 2560,
        height: 1707,
        contentLocation: "中目黒・代官山",
        datePublished: "2024-09-13",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-04.webp",
        alt: "中目黒の高架下に差し込む夜の光",
        width: 2560,
        height: 1707,
        contentLocation: "代官山",
        datePublished: "2025-02-10",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-05.webp",
        alt: "中目黒の高架下に差し込む夜の光 2",
        width: 2560,
        height: 1707,
        contentLocation: "代官山",
        datePublished: "2025-02-10",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-06.webp",
        alt: "中目黒の高架下に差し込む夜の光 3",
        width: 2560,
        height: 1707,
        contentLocation: "代官山",
        datePublished: "2025-02-10",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-07.webp",
        alt: "中目黒の高架下に差し込む夜の光 4",
        width: 2560,
        height: 1707,
        contentLocation: "代官山",
        datePublished: "2025-02-10",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-08.webp",
        alt: "中目黒の高架下に差し込む夜の光 5",
        width: 2560,
        height: 1707,
        contentLocation: "目黒・品川",
        datePublished: "2025-06-07",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-09.webp",
        alt: "恵比寿から中目黒へ続く川沿いの歩道",
        width: 2560,
        height: 1707,
        contentLocation: "目黒・品川",
        datePublished: "2025-06-07",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-10.webp",
        alt: "恵比寿から中目黒へ続く川沿いの歩道 2",
        width: 2560,
        height: 1707,
        contentLocation: "目黒・品川",
        datePublished: "2025-06-07",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-11.webp",
        alt: "恵比寿から中目黒へ続く川沿いの歩道 3",
        width: 2048,
        height: 2560,
        contentLocation: "目黒・品川",
        datePublished: "2025-06-07",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-12.webp",
        alt: "目黒から品川へ続く線路脇のテールライト",
        width: 2048,
        height: 2560,
        contentLocation: "渋谷・新宿",
        datePublished: "2025-02-01",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-13.webp",
        alt: "目黒から品川へ続く線路脇のテールライト 2",
        width: 1707,
        height: 2560,
        contentLocation: "渋谷・新宿",
        datePublished: "2025-02-01",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-14.webp",
        alt: "笹塚から代々木へ続く歩道橋の光",
        width: 2560,
        height: 1707,
        contentLocation: "渋谷・新宿",
        datePublished: "2025-02-01",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-15.webp",
        alt: "笹塚から代々木へ続く歩道橋の光 2",
        width: 2560,
        height: 1707,
        contentLocation: "渋谷・新宿",
        datePublished: "2025-02-01",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-16.webp",
        alt: "笹塚から代々木へ続く歩道橋の光 3",
        width: 2048,
        height: 2560,
        contentLocation: "新宿〜渋谷",
        datePublished: "2024-09-07",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-17.webp",
        alt: "笹塚から代々木へ続く歩道橋の光 4",
        width: 2048,
        height: 2560,
        contentLocation: "新宿〜渋谷",
        datePublished: "2024-09-07",
      },
      {
        src: "/series-gallery/canal-ribbons/canal-ribbons-18.webp",
        alt: "代々木公園の夕暮れ",
        width: 2560,
        height: 1707,
        contentLocation: "新宿〜渋谷",
        datePublished: "2024-09-07",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 24-70mm F2.8 GM II" },
      { label: "Settings", value: "1/500s · F2.8 · ISO 100" },
    ],
    relatedCta: {
      heading: "街歩きロケのご相談",
      body: "運河沿いのロケーションでは、人の流れと街灯の配置を踏まえた絵作りを含めてご提案します。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "harbor-lanterns",
    title: "Harbor Lanterns",
    year: 2024,
    location: "横浜 · 豊洲",
    palette: "color",
    focus: "urban",
    synopsisEn: "Lights of harbor towns and waterlines, from blue hour into night.",
    synopsis: "港町と水辺に灯る明かりを集め、ブルーアワーからナイトまでの時間軸を綴ったシリーズ。",
    lead: "横浜の港エリアと豊洲のベイエリアを歩き、光が水面や街の装飾に溶ける瞬間を集めました。",
    story:
      "海風によるブレを抑えるため1/160s以上をキープしつつ、光の密度に合わせてNDフィルターで露出をコントロール。色温度は街灯の色に揃え、統一感を持たせています。",
    tags: ["Urban", "Night", "Waterfront"],
    cover: {
      src: "/series-gallery/harbor-lanterns/harbor-lanterns-01.webp",
      alt: "横浜港に立ち並ぶクレーンと夜景",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/harbor-lanterns/harbor-lanterns-02.webp",
      alt: "横浜港に立ち並ぶクレーンと夜景 2",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/harbor-lanterns/harbor-lanterns-01.webp",
        alt: "横浜港に立ち並ぶクレーンと夜景",
        width: 2560,
        height: 1707,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
      },
      {
        src: "/series-gallery/harbor-lanterns/harbor-lanterns-02.webp",
        alt: "横浜港に立ち並ぶクレーンと夜景 2",
        width: 2560,
        height: 1707,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
      },
      {
        src: "/series-gallery/harbor-lanterns/harbor-lanterns-03.webp",
        alt: "横浜港に立ち並ぶクレーンと夜景 3",
        width: 2560,
        height: 1707,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
      },
      {
        src: "/series-gallery/harbor-lanterns/harbor-lanterns-04.webp",
        alt: "横浜港のブルーアワー",
        width: 2560,
        height: 1707,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
      },
      {
        src: "/series-gallery/harbor-lanterns/harbor-lanterns-05.webp",
        alt: "横浜中華街のランタン",
        width: 2048,
        height: 2560,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
      },
      {
        src: "/series-gallery/harbor-lanterns/harbor-lanterns-06.webp",
        alt: "横浜中華街のランタン 2",
        width: 2048,
        height: 2560,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
      },
      {
        src: "/series-gallery/harbor-lanterns/harbor-lanterns-07.webp",
        alt: "横浜中華街のランタン 3",
        width: 1707,
        height: 2560,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
      },
      {
        src: "/series-gallery/harbor-lanterns/harbor-lanterns-08.webp",
        alt: "横浜中華街のランタン 4",
        width: 1707,
        height: 2560,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
      },
      {
        src: "/series-gallery/harbor-lanterns/harbor-lanterns-09.webp",
        alt: "豊洲の水辺に映るライト",
        width: 2560,
        height: 1707,
        contentLocation: "豊洲",
        datePublished: "2025-03-15",
      },
      {
        src: "/series-gallery/harbor-lanterns/harbor-lanterns-10.webp",
        alt: "豊洲の水辺に映るライト 2",
        width: 2560,
        height: 1707,
        contentLocation: "豊洲",
        datePublished: "2025-03-15",
      },
      {
        src: "/series-gallery/harbor-lanterns/harbor-lanterns-11.webp",
        alt: "豊洲の水辺に映るライト 3",
        width: 2560,
        height: 1707,
        contentLocation: "豊洲",
        datePublished: "2025-03-15",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 35mm F1.4 GM" },
      { label: "Settings", value: "1/1000s · F8 · ISO 3200" },
    ],
    relatedCta: {
      heading: "ナイトシティ撮影のご相談",
      body: "港町や水辺での長時間露光が必要な案件では、潮汐と風速を考慮したロケーション設計をご提案します。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "elevated-citylines",
    title: "Elevated Citylines",
    year: 2025,
    location: "新宿 · 大手町 · 市ヶ谷・飯田橋",
    palette: "color",
    focus: "urban",
    synopsisEn: "The city seen from above — layered streetscapes around first light.",
    synopsis: "高層ビルや展望台から都市を俯瞰し、夜明け前後の街のレイヤーを切り取ったシリーズ。",
    lead: "新宿と皇居周辺を軸に、夜景からブルーアワーまでの時間帯でビル群と交通の流れを追いました。",
    story:
      "超広角と中望遠を切り替えながら、手持ちでの手ブレ限界と三脚不可の制約の中で露出を整え、ネオンと街灯の色を保つよう調整しています。",
    tags: ["Urban", "Night", "Viewpoint"],
    cover: {
      src: "/series-gallery/elevated-citylines/elevated-citylines-01.webp",
      alt: "新宿高層ビル群を望む展望",
      width: 1707,
      height: 2560,
    },
    heroImage: {
      src: "/series-gallery/elevated-citylines/elevated-citylines-02.webp",
      alt: "新宿高層ビル群を望む展望 2",
      width: 1707,
      height: 2560,
    },
    gallery: [
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-01.webp",
        alt: "新宿高層ビル群を望む展望",
        width: 1707,
        height: 2560,
        contentLocation: "新宿",
        datePublished: "2025-08-10",
        caption: "展望の窓が夜景を切り取る。",
        statement:
          "展望台のガラス反射を抑えるため、黒いクロスでレンズ周りを覆いながら撮影しました。超広角で歪みが出ない角度を探り、街のラインが均等に広がるポイントに立っています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-02.webp",
        alt: "新宿高層ビル群を望む展望 2",
        width: 1707,
        height: 2560,
        contentLocation: "新宿",
        datePublished: "2025-08-10",
        caption: "都市のラインが雲海のように重なる。",
        statement:
          "早朝の蒼が残る時間に露出を-0.5EVに抑え、ビル群の陰影を強調しました。雲の流れが均一になるまで待ち、三脚禁止のため肘を手すりに固定してブレを防いでいます。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-03.webp",
        alt: "新宿高層ビル群を望む展望 3",
        width: 1707,
        height: 2560,
        contentLocation: "新宿",
        datePublished: "2025-08-10",
        caption: "交差する道路が光の格子を描く。",
        statement:
          "道路の交差が最も立体的に見える角度を探し、45mmで圧縮しました。車列の途切れを避けるため複数回露光を確認し、1/2秒で光跡を伸ばしています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-04.webp",
        alt: "新宿高層ビル群を望む展望 4",
        width: 2560,
        height: 1707,
        contentLocation: "新宿",
        datePublished: "2025-08-10",
        caption: "夜明け前の蒼がビル群を包む。",
        statement:
          "空のグラデーションが残るタイミングに合わせ、ホワイトバランスを4000Kに固定しました。窓の明かりが灯るビルを選び、都市の密度が伝わる構図に整えています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-05.webp",
        alt: "新宿高層ビル群を望む展望 5",
        width: 1707,
        height: 2560,
        contentLocation: "新宿",
        datePublished: "2025-08-10",
        caption: "高層のリズムが街の息を整える。",
        statement:
          "ビルの縦線が画面内で均等になるよう、足場を数センチずつ調整しました。露出を少しアンダーにし、外周の暗部が締まるようコントラストをコントロールしています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-06.webp",
        alt: "新宿の夜景と光跡",
        width: 2560,
        height: 1707,
        contentLocation: "新宿",
        datePublished: "2024-10-15",
        caption: "ネオンの流れが街路を染める。",
        statement:
          "ネオンの切り替わりをメモし、色が滑らかに移ろう瞬間を待ちました。レンズフレアを抑えるためフードを密着させ、1/3秒で光の帯を滑らかに描いています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-07.webp",
        alt: "新宿の夜景と光跡 2",
        width: 2560,
        height: 1707,
        contentLocation: "新宿",
        datePublished: "2024-10-17",
        caption: "交差点の光跡が都市の呼吸を描く。",
        statement:
          "歩行者信号のサイクルを合わせ、車列が整うタイミングでシャッターを切りました。雨上がりの路面が反射する位置を選び、都市の脈動を強調しています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-08.webp",
        alt: "新宿の夜景と光跡 3",
        width: 2560,
        height: 1707,
        contentLocation: "新宿",
        datePublished: "2024-10-17",
        caption: "立体交差が光の帯を編む。",
        statement:
          "立体交差の高さが揃うよう、少し離れた建物から望遠で圧縮しました。ISOを抑えて長秒露光し、光跡が滑らかに繋がるよう1秒に設定しています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-09.webp",
        alt: "新宿の夜景と光跡 4",
        width: 2560,
        height: 1707,
        contentLocation: "新宿",
        datePublished: "2024-10-17",
        caption: "車列のリズムが摩天楼を縁取る。",
        statement:
          "ヘッドライトが途切れない時間帯に合わせて再訪し、手持ちで1/4秒までブレを抑えました。画面端のビルが倒れないよう水平を慎重に合わせています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-10.webp",
        alt: "新宿の夜景と光跡 5",
        width: 2560,
        height: 1707,
        contentLocation: "新宿",
        datePublished: "2025-01-11",
        caption: "夜雲に滲むビルが光を返す。",
        statement:
          "雲が低く降りてきた瞬間を狙い、露出を-0.7EVにして光の滲みを残しました。WBを少し暖めて、ビルの窓明かりが柔らかく見えるトーンに整えています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-11.webp",
        alt: "新宿中央公園の夜明け",
        width: 2560,
        height: 1707,
        contentLocation: "新宿",
        datePublished: "2025-01-11",
        caption: "公園の木々が夜明けの蒼に滲む。",
        statement:
          "夜明け前の蒼時間に合わせ、F4で背景のビルを柔らかくぼかしました。手前の樹木が重ならない位置を探り、湿度を感じるコントラストに抑えています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-12.webp",
        alt: "新宿中央公園の夜明け 2",
        width: 1707,
        height: 2560,
        contentLocation: "新宿中央公園",
        datePublished: "2024-10-20",
        caption: "噴水越しに朝の光が差し込む。",
        statement:
          "噴水のリズムを観察し、最も高く跳ね上がるタイミングで1/500秒に設定しました。逆光で飛沫が輝く位置を探し、露出をわずかにアンダーに抑えています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-13.webp",
        alt: "新宿中央公園の夜明け 3",
        width: 1707,
        height: 2560,
        contentLocation: "新宿中央公園",
        datePublished: "2024-10-20",
        caption: "ベンチが眠気を含んだ光を浴びる。",
        statement:
          "ベンチを主役にするため望遠で圧縮し、背景のビルを柔らかく処理しました。人通りがない時間帯を選び、静けさが伝わるよう露出を抑えています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-14.webp",
        alt: "新宿中央公園の夜明け 4",
        width: 2560,
        height: 1707,
        contentLocation: "新宿中央公園",
        datePublished: "2024-10-20",
        caption: "歩道のラインが都市の目覚めを導く。",
        statement:
          "歩道のラインが対角に走る構図を作り、ローアングルで奥行きを出しました。光が路面を滑る時間帯に合わせ、ハイライトを飛ばさないようヒストグラムを確認しています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-15.webp",
        alt: "皇居外苑のライトトレイル",
        width: 2560,
        height: 1707,
        contentLocation: "皇居外苑",
        datePublished: "2025-02-28",
        caption: "堀のカーブがライトトレイルを抱く。",
        statement:
          "堀の見下ろし位置を事前にリサーチし、カーブの中心が画面に収まる角度で三脚を固定しました。1秒露光で光跡を滑らかに伸ばし、水面の反射を同時に残しています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-16.webp",
        alt: "皇居外苑のライトトレイル 2",
        width: 2560,
        height: 1707,
        contentLocation: "大手町",
        datePublished: "2025-02-28",
        caption: "欄干越しに日比谷通りの灯が走る。",
        statement:
          "欄干のデザインを活かすため、前ボケとして画面下に配置しました。車の列が整うまで数本見送り、露出を-0.5EVにして夜景の色を引き締めています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-17.webp",
        alt: "皇居外苑のライトトレイル 3",
        width: 2560,
        height: 1707,
        contentLocation: "大手町",
        datePublished: "2025-02-28",
        caption: "車列の軌跡が皇居の縁に沿う。",
        statement:
          "車道のカーブが最も美しく見える位置を探り、望遠で圧縮しました。信号サイクルを数え、光跡が途切れず繋がる1.3秒に設定しています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-18.webp",
        alt: "皇居外苑のライトトレイル 4",
        width: 2560,
        height: 1707,
        contentLocation: "大手町",
        datePublished: "2025-02-28",
        caption: "水面に反射したヘッドライトが揺れる。",
        statement:
          "風が止む瞬間を待ち、水面の揺れが最小になるタイミングで撮影しました。偏光を弱めて反射を残し、露出を-0.3EVに抑えて光の芯を守っています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-19.webp",
        alt: "九段下の朝霧とビル群",
        width: 1707,
        height: 2560,
        contentLocation: "大手町",
        datePublished: "2025-02-28",
        caption: "朝霧が九段下のビルを霞ませる。",
        statement:
          "霧の濃さが刻々と変わるため、連続で露出を変えながら撮影しました。逆光で浮かぶ粒を捉えるため1/160秒に設定し、靄の柔らかさを残しています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-20.webp",
        alt: "九段下の朝霧とビル群 2",
        width: 1707,
        height: 2560,
        contentLocation: "市ヶ谷・飯田橋",
        datePublished: "2024-11-22",
        caption: "霞の中で高層が輪郭を現す。",
        statement:
          "ビルの輪郭がわずかに見える濃さを狙い、露出を+0.3EVにして白く飛び過ぎないよう調整しました。縦構図で高さを誇張し、霧のレイヤーを引き出しています。",
      },
      {
        src: "/series-gallery/elevated-citylines/elevated-citylines-21.webp",
        alt: "九段下の朝霧とビル群 3",
        width: 2560,
        height: 1707,
        contentLocation: "市ヶ谷・飯田橋",
        datePublished: "2024-11-22",
        caption: "日差しが坂道の影を引き延ばす。",
        statement:
          "坂道の影が伸びる朝の時間帯に合わせ、ローアングルで影の線を強調しました。人の足取りが重ならないタイミングを待ち、都市の目覚めを一枚に凝縮しています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α1 II (ILCE-1M2)" },
      { label: "Lens", value: "FE 55mm F1.8 ZA" },
      { label: "Settings", value: "1/500s · F5.6 · ISO 250" },
    ],
    relatedCta: {
      heading: "展望ロケーション撮影のご相談",
      body: "三脚制限や入場制限がある施設での撮影も、時間帯調整や申請を含めてコーディネートします。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "spring-sanctuaries",
    title: "Spring Sanctuaries",
    year: 2025,
    location: "九段下（夜桜） · 目黒川 · 井の頭公園",
    palette: "color",
    focus: "nature",
    synopsisEn: "Parks and gardens across the city, holding early-spring damp and light.",
    synopsis: "都市に点在する公園と庭園を巡り、春先の湿度と光を収めたアーバンネイチャー。",
    lead: "東京から横浜までの公園や庭園を移動しながら、桜や新緑が街の空気と混ざり合う瞬間を収集しました。",
    story:
      "開園時間と天候をこまめにチェックし、柔らかい曇天や朝の逆光を狙って撮影。望遠で圧縮した枝ぶりと広角で捉えた水辺を組み合わせ、都市と自然の密度を再構成しています。",
    tags: ["Seasonal", "Garden", "Nature"],
    cover: {
      src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-01.webp",
      alt: "都心を彩る桜のアーチ",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-02.webp",
      alt: "都心を彩る桜のアーチ 2",
      width: 1707,
      height: 2560,
    },
    gallery: [
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-01.webp",
        alt: "都心を彩る桜のアーチ",
        width: 2560,
        height: 1707,
        contentLocation: "九段下（夜桜）",
        datePublished: "2025-03-28",
        caption: "水面の桜が街の色を映し返す。",
        statement:
          "ボートが動き出す前の静けさを狙い、ハーフNDで空の輝度を抑えて水面の反射を整えました。風が止む一拍を待ってシャッターを切り、街のライトと花の色調を揃えています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-02.webp",
        alt: "都心を彩る桜のアーチ 2",
        width: 1707,
        height: 2560,
        contentLocation: "九段下（夜桜）",
        datePublished: "2025-03-28",
        caption: "見上げた空が花の膜で覆われる。",
        statement:
          "縦構図でトンネルの奥行きを作り、枝の重なりが詰まり過ぎない位置まで後退しました。舞い落ちる花弁が流れないよう1/250秒で切り取り、空の青を少し残しています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-03.webp",
        alt: "都心を彩る桜のアーチ 3",
        width: 2560,
        height: 1707,
        contentLocation: "目黒川",
        datePublished: "2025-03-29",
        caption: "遊歩道の桜が淡いアーチを描く。",
        statement:
          "歩道のカーブが最も綺麗に見える角度を探り、ローアングルで枝ぶりを強調しました。露出を-0.3EVに抑え、花の密度と手前のリズムが読み取れるようにしています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-04.webp",
        alt: "都心を彩る桜のアーチ 4",
        width: 1707,
        height: 2560,
        contentLocation: "目黒川",
        datePublished: "2025-03-29",
        caption: "枝ぶりが春のリズムを空に刻む。",
        statement:
          "強い日差しで白飛びしやすかったため、露出を抑えて枝のラインを先に決めました。空の彩度を少し落とし、桜の淡いトーンが浮き上がるよう微調整しています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-05.webp",
        alt: "井の頭恩賜公園の池と木漏れ日",
        width: 2560,
        height: 1707,
        contentLocation: "井の頭公園",
        datePublished: "2025-01-13",
        caption: "池の光が桜色をゆらめかせる。",
        statement:
          "偏光フィルターを半分だけ効かせ、反射と水中の色を同時に残しました。ボートの波紋が収まるタイミングを待ち、シャッターを1/30秒まで落として柔らかな揺らぎを描いています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-06.webp",
        alt: "井の頭恩賜公園の池と木漏れ日 2",
        width: 2560,
        height: 1707,
        contentLocation: "井の頭公園",
        datePublished: "2025-01-13",
        caption: "水面に落ちる花弁が波紋を描く。",
        statement:
          "花弁の降り方を観察し、風が弱まる瞬間にシャッターを切りました。露出をわずかにアンダーにしてハイライトを守り、波紋の陰影を丁寧に残しています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-07.webp",
        alt: "井の頭恩賜公園の池と木漏れ日 3",
        width: 2560,
        height: 1707,
        contentLocation: "井の頭公園",
        datePublished: "2025-01-13",
        caption: "木漏れ日と新緑が湿度を映す。",
        statement:
          "レンズヒーターで曇りを防ぎながら、逆光で透ける葉を狙いました。F4で奥のボケを保ち、湿度を感じるコントラストに抑えています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-08.webp",
        alt: "井の頭恩賜公園の池と木漏れ日 4",
        width: 2560,
        height: 1707,
        contentLocation: "井の頭公園",
        datePublished: "2025-01-13",
        caption: "静かな水辺に枝影が重なる。",
        statement:
          "池面の黒が重くならないよう露出を微妙に上げ、シャドウを残しました。枝の配置を整えるため数歩ずつ位置を変え、重なり過ぎない瞬間を選んでいます。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-09.webp",
        alt: "上野恩賜公園の散策路",
        width: 1707,
        height: 2560,
        contentLocation: "上野・浅草",
        datePublished: "2024-12-18",
        caption: "上野の散策路に柔らかな朝霧が漂う。",
        statement:
          "霧が薄くなる直前を狙い、シャッター速度を1/100秒に落として空気の質感を拾いました。石畳の連なりが奥へ伸びるよう、画面端の垂直を丁寧に合わせています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-10.webp",
        alt: "上野恩賜公園の散策路 2",
        width: 2560,
        height: 1707,
        contentLocation: "上野・浅草",
        datePublished: "2024-12-18",
        caption: "レンガの手すりが春の気配を導く。",
        statement:
          "手すりのリズムを活かすために斜めから構え、前景を少しぼかして奥行きを出しました。人物の影が入らないタイミングを待ち、露出を-0.3EVに抑えています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-11.webp",
        alt: "上野恩賜公園の散策路 3",
        width: 2560,
        height: 1707,
        contentLocation: "上野・浅草",
        datePublished: "2024-12-18",
        caption: "小径の先で桜の影が重なり合う。",
        statement:
          "フォーカスピーキングで手前の桜を合わせ、奥の光が滲むよう開放寄りで撮影しました。背景の看板が目立たない角度を探り、画面全体のトーンを揃えています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-12.webp",
        alt: "上野動物園の朝の光",
        width: 2560,
        height: 1707,
        contentLocation: "上野動物園",
        datePublished: "2025-05-24",
        caption: "温室の光が湿度を柔らかく散らす。",
        statement:
          "温室内の高湿度でレンズが曇るため、ドライクロスでこまめに拭きながら撮影しました。曇ったガラス越しの光を活かすため、露出をややプラスに振っています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-13.webp",
        alt: "上野動物園の朝の光 2",
        width: 2560,
        height: 1707,
        contentLocation: "上野動物園",
        datePublished: "2025-05-24",
        caption: "ガラス越しの呼気が朝陽に滲む。",
        statement:
          "ガラス面の水滴が映る角度を探し、奥のハイライトが飛び過ぎないよう露出を調整しました。手前のボケを厚くすることで湿度のレイヤーを強調しています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-14.webp",
        alt: "三溪園の池と古建築",
        width: 2560,
        height: 1707,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
        caption: "三溪園の池が古建築を静止画に写す。",
        statement:
          "池面が静かになる風待ちをしながら、偏光を弱めて反射を残しました。建物の輪郭が沈まないよう、わずかにシャドウを持ち上げています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-15.webp",
        alt: "三溪園の池と古建築 2",
        width: 2560,
        height: 1707,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
        caption: "枝垂れ桜が屋根に寄り添う。",
        statement:
          "望遠で圧縮し、屋根瓦と花の距離感を詰めました。枝がフレームアウトしない位置を探り、わずかな揺れを抑えるため1/200秒に設定しています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-16.webp",
        alt: "三溪園の池と古建築 3",
        width: 2560,
        height: 1707,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
        caption: "灯籠と池が春宵を映し出す。",
        statement:
          "ライトアップの色が飽和しないよう露出を-1EVに落とし、水面の反射を優先しました。灯籠の位置関係を整えるため、数センチ単位で三脚を移動しています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-17.webp",
        alt: "靖国神社参道の桜",
        width: 2048,
        height: 2560,
        contentLocation: "靖国神社",
        datePublished: "2025-04-17",
        caption: "靖国の参道に桜色のトンネルが生まれる。",
        statement:
          "参道を歩く人が途切れる時間帯を狙い、ハイライトが飛ばないよう露出を抑えました。鳥居の柱が歪まないよう中央に立ち、水平を慎重に合わせています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-18.webp",
        alt: "靖国神社参道の桜 2",
        width: 2048,
        height: 2560,
        contentLocation: "靖国神社",
        datePublished: "2025-04-17",
        caption: "石鳥居と花の淡い呼吸が重なる。",
        statement:
          "鳥居と花房のバランスを取るため、ステップを上下して最適な高さを探りました。彩度を少し落として石の質感を残し、花の柔らかさを浮かび上がらせています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-19.webp",
        alt: "新宿御苑の冬枯れと緑",
        width: 1707,
        height: 2560,
        contentLocation: "新宿御苑・代々木",
        datePublished: "2025-03-20",
        caption: "冬枯れの芝が早春の光を受け止める。",
        statement:
          "光が芝に斜めに入る時間を待ち、影のグラデーションを強調しました。望遠で圧縮し、常緑との対比が伝わるよう被写界深度を浅く保っています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-20.webp",
        alt: "新宿御苑の冬枯れと緑 2",
        width: 1707,
        height: 2560,
        contentLocation: "新宿御苑・代々木",
        datePublished: "2025-03-20",
        caption: "池の縁に常緑と枯色が並ぶ。",
        statement:
          "色のコントラストを際立たせるためホワイトバランスを少し暖め、露出を-0.3EVに設定しました。水面の反射が主題を邪魔しないよう、角度を微調整しています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-21.webp",
        alt: "新宿御苑の冬枯れと緑 3",
        width: 2560,
        height: 1707,
        contentLocation: "新宿御苑・代々木",
        datePublished: "2025-03-20",
        caption: "雪解けの芝目が柔らかい影を描く。",
        statement:
          "低い位置から芝のテクスチャを拾い、ハイライトが飛ばないようヒストグラムを確認しながら撮影しました。影の線が斜めに走る構図で、季節の移り変わりを表現しています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-22.webp",
        alt: "駒沢公園の並木",
        width: 2560,
        height: 1707,
        contentLocation: "駒沢公園",
        datePublished: "2024-11-04",
        caption: "駒沢の並木が夕方の風を抱き留める。",
        statement:
          "夕暮れの暖色が並木を照らすタイミングを狙い、シャッターを1/125秒にして葉の揺れを残しました。歩道の白線が邪魔にならないよう、立ち位置を細かく調整しています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-23.webp",
        alt: "駒沢公園の並木 2",
        width: 2560,
        height: 1707,
        contentLocation: "駒沢公園",
        datePublished: "2024-11-04",
        caption: "ランナーの視線を導く並木のアーチ。",
        statement:
          "ランナーの流れを観察し、人物が自然に入るまで待ちました。望遠で圧縮してアーチの密度を高め、被写界深度を浅くすることで視線を奥へ誘導しています。",
      },
      {
        src: "/series-gallery/spring-sanctuaries/spring-sanctuaries-24.webp",
        alt: "駒沢公園の並木 3",
        width: 2560,
        height: 1707,
        contentLocation: "駒沢公園",
        datePublished: "2024-11-04",
        caption: "トラック沿いの木々が夕暮れの粒を散らす。",
        statement:
          "トラックのカーブが美しく見える角度を探り、露出を-0.5EVにして木漏れ日の粒を浮かせました。背景のビルが目立たないよう、低めの視点で切り取っています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α1 II (ILCE-1M2)" },
      { label: "Lens", value: "FE 35mm F1.4 GM" },
      { label: "Settings", value: "1/4s · F2 · ISO 100" },
    ],
    relatedCta: {
      heading: "撮影のご相談はこちら",
      body: "シリーズに合わせたロケーション提案やスケジュール設計から撮影・納品まで一貫して対応します。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "morning-transit",
    title: "Morning Transit",
    year: 2025,
    location: "東京駅 · 浜松町 · 渋谷",
    palette: "color",
    focus: "people",
    synopsisEn: "From the first train to the rush — the hour the city stands up.",
    synopsis: "始発から通勤ラッシュまで、朝の都市が立ち上がる時間を切り取った記録。",
    lead: "始業前の東京を歩き、人の気配と柔らかな朝光が重なる瞬間を追いかけたシリーズ。",
    story:
      "始発に合わせて駅舎や高架の影を計算し、手持ちの高速シャッターと流し撮りを組み合わせて朝の空気感を立ち上げています。",
    tags: ["Urban", "People", "Morning"],
    cover: {
      src: "/series-gallery/morning-transit/morning-transit-01.webp",
      alt: "朝焼けに染まる東京駅丸の内駅舎と往来する人影",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/morning-transit/morning-transit-01.webp",
      alt: "朝焼けに染まる東京駅丸の内駅舎と往来する人影",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/morning-transit/morning-transit-01.webp",
        alt: "朝焼けに染まる東京駅丸の内駅舎と往来する人影",
        width: 2560,
        height: 1707,
        contentLocation: "東京駅",
        datePublished: "2024-10-31",
        caption: "丸の内の心拍が朝陽でゆっくり動き出す。",
        statement:
          "始発前の静けさが解ける瞬間を待ちながら、三脚なしで街の鼓動を拾いました。赤煉瓦の色が過剰にならないよう、露出を微妙に抑えて柔らかな立ち上がりを残しています。",
      },
      {
        src: "/series-gallery/morning-transit/morning-transit-02.webp",
        alt: "東京駅前の石畳に伸びる朝のシルエット",
        width: 2560,
        height: 1707,
        contentLocation: "東京駅",
        datePublished: "2024-10-31",
        caption: "石畳に落ちた影が朝のテンポを描き出す。",
        statement:
          "足音が増える前に俯瞰せず路面ギリギリで構え、影がリズムを刻む様子を追いました。石畳の反射が飛ばないよう偏光を弱めに設定しています。",
      },
      {
        src: "/series-gallery/morning-transit/morning-transit-03.webp",
        alt: "八重洲側のガラスに映る朝日と通勤客の流れ",
        width: 2560,
        height: 1707,
        contentLocation: "東京駅",
        datePublished: "2024-10-31",
        caption: "ガラスに跳ねた朝陽が人の流れを二重写しにする。",
        statement:
          "八重洲のビル風が強く三脚が使えなかったので、ガラスへの映り込みを手持ちで丁寧に追いかけました。映り込みと実像のコントラストを揃えるため、WBは太陽光に固定しています。",
      },
      {
        src: "/series-gallery/morning-transit/morning-transit-04.webp",
        alt: "浜松町の高架下を通り抜ける通勤者の列",
        width: 2560,
        height: 1707,
        contentLocation: "浜松町",
        datePublished: "2025-01-26",
        caption: "高架の影が通勤者の列に呼吸を与える。",
        statement:
          "高架下の暗部が潰れないよう、ISOを上げつつシャッター速度を1/320sにキープ。列が途切れるタイミングを見計らい、奥の明かりと手前の影を同じバランスで収めました。",
      },
      {
        src: "/series-gallery/morning-transit/morning-transit-05.webp",
        alt: "縦構図で捉えた浜松町の歩道橋と逆光の通勤者",
        width: 2048,
        height: 2560,
        contentLocation: "浜松町",
        datePublished: "2025-01-26",
        caption: "逆光のなかで一歩目が宙に浮く。",
        statement:
          "縦位置で逆光を受けた歩道橋のリズムを強調しました。人影が重なりすぎないよう何度も往復し、靴の上がる瞬間と街の線が交差するタイミングでシャッターを切っています。",
      },
      {
        src: "/series-gallery/morning-transit/morning-transit-06.webp",
        alt: "浜松町の街路と首都高に差し込む柔らかなハイライト",
        width: 2560,
        height: 1707,
        contentLocation: "浜松町",
        datePublished: "2025-01-26",
        caption: "首都高の影が街路に柔らかな呼吸を残した朝。",
        statement:
          "交通量が落ち着く一瞬を見計らい、路面の光が一番柔らかな時に露出を合わせました。ローアングルからラインを拾い、街路樹の緑がわずかに残る色を活かしています。",
      },
      {
        src: "/series-gallery/morning-transit/morning-transit-07.webp",
        alt: "渋谷の朝活イベント会場に集まる参加者たち",
        width: 2560,
        height: 1707,
        contentLocation: "渋谷",
        datePublished: "2025-01-12",
        caption: "まだ眠い街のなかで声が交わり始める。",
        statement:
          "朝活会場の空気感を崩さないよう、距離を保ちながら長めの焦点距離で切り取りました。参加者同士が目を合わせた瞬間を待ち、会話の輪郭が伝わるよう肌トーンを丁寧に残しています。",
      },
      {
        src: "/series-gallery/morning-transit/morning-transit-08.webp",
        alt: "朝渋の会場で朝日を浴びる参加者のシルエット",
        width: 1707,
        height: 2560,
        contentLocation: "渋谷",
        datePublished: "2025-01-12",
        caption: "窓辺の光がアイデアを照らす。",
        statement:
          "逆光でシルエットを強調し、窓際の白飛びを抑えるために露出を-1EVまで下げました。会話の熱量が静かに立ち上がる時間帯を逃さないよう、連写ではなく呼吸を合わせて一枚に集中しています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 35mm F1.4 GM" },
      { label: "Settings", value: "1/500s · F8 · ISO 2000" },
    ],
    relatedCta: {
      heading: "企業イベント撮影のご相談はこちら",
      body: "朝の時間帯に合わせた段取りと機動力ある撮影体制で、空気感を逃さず記録します。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "sakura-resonance",
    title: "Sakura Resonance",
    year: 2025,
    location: "九段下（夜桜） · 目黒川 · 靖国神社",
    palette: "color",
    focus: "nature",
    synopsisEn: "The season cherry blossoms breathe with the city — a sway of nature and streets.",
    synopsis: "桜が街と呼吸する季節を追い、都市と自然の揺らぎを重ねたストーリー。",
    lead: "桜が街と呼吸する春の音色を集め、都市と自然の境界をやわらかく融かした連作。",
    story:
      "開花予報を追いながら薄曇りと晴れの日を織り交ぜ、偏光フィルターでハイライトを抑えつつ立体感を残しています。",
    tags: ["Seasonal", "Nature", "Color"],
    cover: {
      src: "/series-gallery/sakura-resonance/sakura-resonance-01.webp",
      alt: "千鳥ヶ淵の水面に枝を垂らす満開の桜",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/sakura-resonance/sakura-resonance-01.webp",
      alt: "千鳥ヶ淵の水面に枝を垂らす満開の桜",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/sakura-resonance/sakura-resonance-01.webp",
        alt: "千鳥ヶ淵の水面に枝を垂らす満開の桜",
        width: 2560,
        height: 1707,
        contentLocation: "九段下（夜桜）",
        datePublished: "2025-03-28",
        caption: "水面の揺らぎが桜の呼吸を映し返す朝。",
        statement:
          "千鳥ヶ淵のボートが動き出す前の静寂を狙い、長めのシャッターで水面の表情を柔らかく仕上げました。枝の密度が重くならないよう、画面端を切り詰めて余白を確保しています。",
      },
      {
        src: "/series-gallery/sakura-resonance/sakura-resonance-02.webp",
        alt: "桜のトンネルを見上げる縦構図の柔らかな花びら",
        width: 1707,
        height: 2560,
        contentLocation: "九段下（夜桜）",
        datePublished: "2025-03-28",
        caption: "見上げた空が花の膜で覆われる瞬間。",
        statement:
          "視線を上に誘導したくて、縦構図で奥行きを強調しました。風が吹くたび露が落ちるので、タイミングを合わせて僅かなブレを受け入れつつ花びらに光を残しています。",
      },
      {
        src: "/series-gallery/sakura-resonance/sakura-resonance-03.webp",
        alt: "皇居周辺の遊歩道を染める淡紅色の桜並木",
        width: 2560,
        height: 1707,
        contentLocation: "目黒川",
        datePublished: "2025-03-29",
        caption: "皇居の堀を沿う風が花びらをそっと運ぶ。",
        statement:
          "遊歩道のリズムを崩さないよう、行き交うランナーが途切れる一瞬を待ちました。低めの角度から撮り、手前のガードレールを画面外に押し出して桜だけの世界を維持しています。",
      },
      {
        src: "/series-gallery/sakura-resonance/sakura-resonance-04.webp",
        alt: "枝ぶりを強調した桜と澄んだ春の空",
        width: 1707,
        height: 2560,
        contentLocation: "目黒川",
        datePublished: "2025-03-29",
        caption: "枝の線で空に楽譜を描くように。",
        statement:
          "強い日差しで花弁が飛びやすかったので、露出を抑え枝の質感を優先しました。空の青をわずかに深くし、桜の白とピンクが浮かび上がるようコントラストを整えています。",
      },
      {
        src: "/series-gallery/sakura-resonance/sakura-resonance-05.webp",
        alt: "春の朝日を受ける桜の枝と遠景の都市シルエット",
        width: 2560,
        height: 1707,
        contentLocation: "目黒川",
        datePublished: "2025-03-29",
        caption: "都市の稜線が桜の香りに溶ける。",
        statement:
          "都市のシルエットを背景に残すため、望遠で圧縮しながら前ボケを控えめにしています。朝日の色温度を少し冷やし、桜の柔らかさとビルの硬さの間に余韻をつくりました。",
      },
      {
        src: "/series-gallery/sakura-resonance/sakura-resonance-06.webp",
        alt: "靖国神社参道を彩る重なり合う桜の花房",
        width: 2048,
        height: 2560,
        contentLocation: "靖国神社",
        datePublished: "2025-04-17",
        caption: "参道の静けさに花房が降り積もる。",
        statement:
          "参道を行き交う人を避けるため、早朝に絞りを開けて奥の鳥居を柔らかくぼかしました。重なり合う花房の厚みを出すため、露出補正をプラスにして階調を丁寧に拾っています。",
      },
      {
        src: "/series-gallery/sakura-resonance/sakura-resonance-07.webp",
        alt: "靖国神社の石鳥居と調和する淡い桜色",
        width: 2048,
        height: 2560,
        contentLocation: "靖国神社",
        datePublished: "2025-04-17",
        caption: "石の重さと花の軽さが同じ呼吸になる。",
        statement:
          "鳥居の水平線を崩さないよう三脚を低めに構え、花の重なりが鳥居に触れる位置を探りました。質感を合わせるため、彩度を抑えつつ赤みをほんの少しだけ足しています。",
      },
      {
        src: "/series-gallery/sakura-resonance/sakura-resonance-08.webp",
        alt: "三溪園の古建築と水辺を包む夜桜の光",
        width: 2560,
        height: 1707,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
        caption: "夜の水鏡に灯が点り、季節が静かに巡る。",
        statement:
          "夜桜のライトアップは色が飽和しがちなので、露出を二段アンダーにして水面の反射を優先しました。古建築のラインが沈まないよう、ハイライトをわずかに持ち上げています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α1 II (ILCE-1M2)" },
      { label: "Lens", value: "FE 35mm F1.4 GM" },
      { label: "Settings", value: "1/4s · F2 · ISO 100" },
    ],
    relatedCta: {
      heading: "季節キャンペーン撮影のご相談はこちら",
      body: "桜や季節の移ろいを活かした観光・企業案件に合わせ、事前ロケと光のコントロールをご提案します。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "highland-drift",
    title: "Highland Drift",
    year: 2024,
    location: "那須 · 南湖公園（白河） · 富士五湖",
    palette: "color",
    focus: "nature",
    synopsisEn: "Highlands of Nasu and Fuji, terrain breathing in mist and light.",
    synopsis: "那須と富士の高原を巡り、霧と光が描く地形の呼吸を収集したシリーズ。",
    lead: "山と湖の温度差がつくる霧と光の揺らぎを、滞在制作で積み上げた高原シリーズ。",
    story:
      "夜明け前からの気温差を読み、風の止むタイミングでドローンと地上カメラを切り替えながら層の厚みを構築しました。",
    tags: ["Nature", "Landscape", "Travel"],
    cover: {
      src: "/series-gallery/highland-drift/highland-drift-01.webp",
      alt: "那須の稜線を包む朝霧と紅葉の斜面",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/highland-drift/highland-drift-01.webp",
      alt: "那須の稜線を包む朝霧と紅葉の斜面",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/highland-drift/highland-drift-01.webp",
        alt: "那須の稜線を包む朝霧と紅葉の斜面",
        width: 2560,
        height: 1707,
        contentLocation: "那須",
        datePublished: "2024-11-01",
        caption: "稜線をなぞる霧が夜と朝の境界をほどく。",
        statement:
          "夜明け前から気温を計測し、霧が一番薄くなる瞬間を狙いました。風が吹き抜ける直前にドローンを離陸させ、紅葉の階調が濁らないよう露出を小刻みに調整しています。",
      },
      {
        src: "/series-gallery/highland-drift/highland-drift-02.webp",
        alt: "山並みに差し込む斜光と広がる雲海",
        width: 2560,
        height: 1707,
        contentLocation: "那須",
        datePublished: "2024-11-01",
        caption: "斜光が雲海を撫で、谷の鼓動が目に見える。",
        statement:
          "太陽が顔を出す瞬間に合わせ、シャドウを持ち上げすぎないようRAWで粘りました。斜面のラインが引き立つよう、レンズフレアをカットする角度を探って飛ばしています。",
      },
      {
        src: "/series-gallery/highland-drift/highland-drift-03.webp",
        alt: "高原の尾根道を滑るように流れる雲",
        width: 2560,
        height: 1707,
        contentLocation: "那須",
        datePublished: "2024-11-01",
        caption: "尾根の上に手書きの線のような雲が走る。",
        statement:
          "雲の流れが速かったので、シャッターをやや遅くしてスローシャッターぎみに撮影しました。尾根の質感を保つため、三脚を低く構え風の振動を抑えています。",
      },
      {
        src: "/series-gallery/highland-drift/highland-drift-04.webp",
        alt: "南湖公園の湖畔に映る紅葉と青い空",
        width: 2560,
        height: 1707,
        contentLocation: "南湖公園（白河）",
        datePublished: "2024-11-01",
        caption: "湖面が秋色の記憶を逆さまに抱きしめる。",
        statement:
          "湖面が揺れない風待ちをしながら偏光を調整し、反射と透過のバランスを探りました。手前の落ち葉をあえてフレームに入れ、季節の厚みを足しています。",
      },
      {
        src: "/series-gallery/highland-drift/highland-drift-05.webp",
        alt: "黄金色の並木が南湖公園の遊歩道を彩る",
        width: 2560,
        height: 1707,
        contentLocation: "南湖公園（白河）",
        datePublished: "2024-11-01",
        caption: "遊歩道が金色の風に包まれる午後。",
        statement:
          "遊歩道を歩く人が少ないタイミングで、ローアングルから並木の高さを誇張しました。光が硬くなりすぎないよう、露出はアンダーに振って後処理でシャドウを起こしています。",
      },
      {
        src: "/series-gallery/highland-drift/highland-drift-06.webp",
        alt: "湖面へ延びる木道と静かな水の表情",
        width: 2560,
        height: 1707,
        contentLocation: "南湖公園（白河）",
        datePublished: "2024-11-01",
        caption: "木道が静かな水面へ手を伸ばす。",
        statement:
          "木道の線が真っ直ぐ見えるよう、センターから外して構図を取り直しました。霞んだ空を取り込みすぎないよう、フレーム上部を詰めて視線を誘導しています。",
      },
      {
        src: "/series-gallery/highland-drift/highland-drift-07.webp",
        alt: "富士吉田の街越しにそびえる富士山と夜明けの光",
        width: 2560,
        height: 1707,
        contentLocation: "富士五湖",
        datePublished: "2025-08-02",
        caption: "街の灯が消え、山が光を引き継ぐ夜明け。",
        statement:
          "街の明かりが消える直前の数分を狙い、ダイナミックレンジが広くなる時間帯に合わせました。富士山の稜線が滲まないよう、ホワイトバランスを少し暖めています。",
      },
      {
        src: "/series-gallery/highland-drift/highland-drift-08.webp",
        alt: "富士山を背景に伸びる街のライトトレイル",
        width: 2560,
        height: 1707,
        contentLocation: "富士五湖",
        datePublished: "2025-08-02",
        caption: "ライトトレイルが山麓の呼吸をなぞる。",
        statement:
          "車の往来が安定する時間帯に合わせ、複数の露光を重ねず一枚で勝負しました。ライトトレイルが繋がるよう1/4秒に設定し、山のシルエットにノイズが乗らないようISOを抑えています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 III (ILCE-7M3)" },
      { label: "Lens", value: "FE 70-200mm F2.8 GM OSS II" },
      { label: "Settings", value: "1/500s · F8 · ISO 320" },
    ],
    relatedCta: {
      heading: "観光・地域ブランディングの撮影相談",
      body: "山岳や湖沼の撮影では天候待機や複数日程のレイヤー構成までサポートします。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "harbor-blue-hour",
    title: "Harbor Blue Hour",
    year: 2024,
    location: "横浜 · 豊洲",
    palette: "color",
    focus: "urban",
    synopsisEn: "The harbor's blue hour, walking the edge between city and sea.",
    synopsis: "港のブルーアワーがつなぐ都市と海の境界を歩いたナイトシリーズ。",
    lead: "港のブルーアワーが映す都市と海の境界を歩き、夜へ溶けゆく時間を捉えたシリーズ。",
    story:
      "潮汐とライトアップのスケジュールを合わせ、水面反射が最大になる時間帯に合わせて露光と色温度をコントロールしました。",
    tags: ["Urban", "Night", "Waterfront"],
    cover: {
      src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-01.webp",
      alt: "横浜みなとみらいの観覧車と高層ビルが灯る青の時間",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-01.webp",
      alt: "横浜みなとみらいの観覧車と高層ビルが灯る青の時間",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-01.webp",
        alt: "横浜みなとみらいの観覧車と高層ビルが灯る青の時間",
        width: 2560,
        height: 1707,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
        caption: "潮風が色を溶かすブルーアワーの鼓動。",
        statement:
          "観覧車のライトが切り替わる周期をメモし、色が最も滑らかに移ろう瞬間を狙いました。海風で三脚が揺れるのでストラップを固定し、映り込みの線が崩れないよう粘っています。",
      },
      {
        src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-02.webp",
        alt: "縦構図で捉えたランドマークタワーと光る運河",
        width: 1707,
        height: 2560,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
        caption: "タワーの縦線が運河の静けさを支える。",
        statement:
          "ランドマークタワーの直線を主役にしたくて、縦構図で運河の反射を引き伸ばしました。空の色が残る時間帯に合わせ、露出をアンダー寄りに調整しています。",
      },
      {
        src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-03.webp",
        alt: "横浜港の水面に映るライトと観覧車の残光",
        width: 2560,
        height: 1707,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
        caption: "水面に描かれた光のリボンが夜へ誘う。",
        statement:
          "波の周期が落ち着くまで待ち、1/2秒で滑らかな反射を描きました。ライトが飽和しないよう、ハイライトをマイナス補正しながら色のグラデーションを維持しています。",
      },
      {
        src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-04.webp",
        alt: "汽車道から望むみなとみらいの夜景と水辺",
        width: 2560,
        height: 1706,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
        caption: "汽車道の線路跡が海と街をつなぐ橋になる。",
        statement:
          "旧線路のテクスチャを活かすため、ローアングルで前景をしっかり入れました。橋を渡る人の流れが切れる瞬間を待ち、開放寄りで背景を柔らかく落としています。",
      },
      {
        src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-05.webp",
        alt: "横浜中華街の門を飾る赤い提灯と街灯",
        width: 1707,
        height: 2560,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
        caption: "提灯の赤が夜気を温める路地口。",
        statement:
          "門の色が飽和しないよう、色温度を低めの3200Kに固定しました。提灯が風で揺れるたびに表情が変わるので、連写ではなく揺れが落ち着くタイミングを見極めています。",
      },
      {
        src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-06.webp",
        alt: "横浜中華街の路地を照らす提灯と歩行者の流れ",
        width: 2560,
        height: 1707,
        contentLocation: "横浜",
        datePublished: "2024-11-08",
        caption: "路地の温度を行き交う人が運んでいく。",
        statement:
          "路面の濡れ具合を残すため、雨上がり直後に撮影しました。歩行者の足取りがぶれすぎないよう1/60秒に設定し、提灯の光に包まれた空気感を優先しています。",
      },
      {
        src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-07.webp",
        alt: "豊洲の運河沿いに並ぶガラスファサードの夜景",
        width: 2560,
        height: 1707,
        contentLocation: "豊洲",
        datePublished: "2025-03-15",
        caption: "ガラスの肌が潮風の色を集める。",
        statement:
          "ガラスの反射が複雑だったので、一歩ずつ位置を変えながら街灯の映り込みを整理しました。運河の暗部が潰れないよう、ハイダイナミックなRAW現像を前提に露出を決めています。",
      },
      {
        src: "/series-gallery/harbor-blue-hour/harbor-blue-hour-08.webp",
        alt: "豊洲ベイエリアに集まるライトアップされたビル群",
        width: 2560,
        height: 1707,
        contentLocation: "豊洲",
        datePublished: "2025-03-15",
        caption: "湾岸の灯りが夜を柔らかく抱く。",
        statement:
          "ビルの照明が全点灯する時間帯に合わせ、手前のフェンスが入らない位置を探りました。遠景の色が濁らないよう、ミッドトーンを落としてクリアな蒼を残しています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 35mm F1.4 GM" },
      { label: "Settings", value: "1/1000s · F8 · ISO 3200" },
    ],
    relatedCta: {
      heading: "ナイトロケーションのご相談はこちら",
      body: "港湾エリアやウォーターフロントの案件に、ドローンやタイムラプスを組み合わせた提案が可能です。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "winter-gleam",
    title: "Winter Gleam",
    year: 2025,
    location: "日出づる里 · ハンターマウンテン塩原",
    palette: "color",
    focus: "motion",
    synopsisEn: "First sunrise and moving snowfields — a story of winter light.",
    synopsis: "初日の出と雪山の躍動を束ねた冬の光のストーリー。",
    lead: "初日の出と雪山の光を追い、冬の張り詰めた空気と躍動を束ねたシリーズ。",
    story:
      "極寒環境での露結を避けるためヒーターを用意し、ゲレンデでは追い撮りと遠望を組み合わせてスピード感を表現しています。",
    tags: ["Seasonal", "Motion", "Adventure"],
    cover: {
      src: "/series-gallery/winter-gleam/winter-gleam-01.webp",
      alt: "日出づる里から望む元旦のダイヤモンド富士",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/winter-gleam/winter-gleam-01.webp",
      alt: "日出づる里から望む元旦のダイヤモンド富士",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/winter-gleam/winter-gleam-01.webp",
        alt: "日出づる里から望む元旦のダイヤモンド富士",
        width: 2560,
        height: 1707,
        contentLocation: "日出づる里",
        datePublished: "2025-01-01",
        caption: "一年の最初の光が、富士の肩を赤く染める。",
        statement:
          "夜明け前から、富士山頂が雲に隠れない位置まで歩いて構えました。温度差でレンズが曇らないようヒーターを使い、冷えた朝の空気の透明感をそのまま写し取っています。",
      },
      {
        src: "/series-gallery/winter-gleam/winter-gleam-02.webp",
        alt: "冷えた朝の光に浮かぶ富士の稜線",
        width: 2560,
        height: 1707,
        contentLocation: "日出づる里",
        datePublished: "2025-01-01",
        caption: "冷えた風が、金色にほどけていく。",
        statement:
          "光が動く速度に合わせ、1/160秒で山際の粒立ちを止めました。ハイライトが飛ばないよう露出を落とし、冷えた空気の透明感を残しています。",
      },
      {
        src: "/series-gallery/winter-gleam/winter-gleam-03.webp",
        alt: "富士山頂に立つ、一年最初の光",
        width: 2560,
        height: 1707,
        contentLocation: "日出づる里",
        datePublished: "2025-01-01",
        caption: "頂の上に、光がひとつ立つ。",
        statement:
          "太陽が高くなる前に、頂と光が重なる角度を探しました。稜線のラインが綺麗に伸びる位置を選び、光が乗るまでシャッターを数枚重ねています。",
      },
      {
        src: "/series-gallery/winter-gleam/winter-gleam-04.webp",
        alt: "初日の出の空を染める雲と遠くの山並み",
        width: 2560,
        height: 1707,
        contentLocation: "日出づる里",
        datePublished: "2025-01-01",
        caption: "雲が夜を抱きしめたまま色を変える。",
        statement:
          "雲の層が分厚かったので、露出ブラケットを最小限に抑えRAWで粘りました。山並みのディテールが失われないよう、ホワイトバランスを少しだけ暖色に寄せています。",
      },
      {
        src: "/series-gallery/winter-gleam/winter-gleam-05.webp",
        alt: "ハンターマウンテン塩原のゲレンデを滑るスノーボーダー",
        width: 2560,
        height: 1707,
        contentLocation: "ハンターマウンテン塩原",
        datePublished: "2025-02-24",
        caption: "雪面を切り裂く一瞬が冬の疾走感を描く。",
        statement:
          "ライダーと無線で合図を取りながら、逆光でスプレーが最も輝く角度を合わせました。高速シャッターで雪の粒を止め、背景の樹木が煩雑にならない位置まで移動しています。",
      },
      {
        src: "/series-gallery/winter-gleam/winter-gleam-06.webp",
        alt: "雪面に描かれたターンの軌跡と舞い上がる粉雪",
        width: 2560,
        height: 1707,
        contentLocation: "ハンターマウンテン塩原",
        datePublished: "2025-02-24",
        caption: "ターンの軌跡が白紙の上に筆跡を刻む。",
        statement:
          "直前の滑走でついたラインを活かすため、雪面を踏み荒らさないよう遠回りしてポジションを取りました。粉雪が均一に舞う風待ちをし、連写で軌跡の最も美しい瞬間を選んでいます。",
      },
      {
        src: "/series-gallery/winter-gleam/winter-gleam-07.webp",
        alt: "雪山を滑走するスノーボーダーのシルエット",
        width: 2560,
        height: 1707,
        contentLocation: "ハンターマウンテン塩原",
        datePublished: "2025-02-24",
        caption: "逆光のシルエットが冬の濃度を引き締める。",
        statement:
          "太陽を背に滑ってもらい、人物の輪郭をシンプルに切り取りました。雪面が飽和しないよう露出をさらに-0.7EV下げ、青い影のグラデーションを強調しています。",
      },
      {
        src: "/series-gallery/winter-gleam/winter-gleam-08.webp",
        alt: "山頂から見下ろす白銀の森と滑走跡",
        width: 2560,
        height: 1707,
        contentLocation: "ハンターマウンテン塩原",
        datePublished: "2025-02-24",
        caption: "白銀の森に刻まれた軌跡が旅の地図になる。",
        statement:
          "ゴンドラの始発で山頂に上がり、誰のトラックも入っていない斜面を待ちました。複数カットを重ねず一枚で仕上げ、雪面の立体感が出るようコントラストを丁寧に調整しています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 70-200mm F2.8 GM OSS II" },
      { label: "Settings", value: "1/500s · F3.5 · ISO 5000" },
    ],
    relatedCta: {
      heading: "ウィンターイベントの撮影相談",
      body: "雪山や初日の出など寒冷地ロケでは、安全管理と機材冗長化を含めた体制をご用意します。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "ueno-arcadia",
    title: "Ueno Arcadia",
    year: 2025,
    location: "上野動物園 · 上野・浅草 · 浅草",
    palette: "color",
    focus: "nature",
    synopsisEn: "Morning light on Ueno's woods and Inokashira's water — an urban-nature series.",
    synopsis: "上野の杜と井の頭の水面に宿る朝の光を編んだアーバンネイチャーシリーズ。",
    lead: "上野と井の頭を巡り、冬の柔らかな光としっとりした空気を層にした散策記録。街と緑が溶け合う時間帯を拾い集めました。",
    story:
      "開園直後の静けさを狙い、動物園では望遠で圧縮しながら木漏れ日を捉え、公園では偏光フィルターで水面の反射を整えました。霧が出た瞬間は露出を-0.7EVまで落としてハイライトを保っています。",
    tags: ["Nature", "Morning", "Urban Park"],
    cover: {
      src: "/series-gallery/ueno-arcadia/ueno-arcadia-01.webp",
      alt: "上野動物園の園路に差し込む朝の光",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/ueno-arcadia/ueno-arcadia-01.webp",
      alt: "上野動物園の園路に差し込む朝の光",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/ueno-arcadia/ueno-arcadia-01.webp",
        alt: "上野動物園の園路を包む柔らかな朝のハイライト",
        width: 2560,
        height: 1707,
        contentLocation: "上野動物園",
        datePublished: "2025-05-24",
        caption: "園路に差す朝の光が一日の扉を開ける。",
        statement:
          "開園直後の静けさを逃さないよう、ゲート前で並んでからダッシュでポイントに立ちました。木漏れ日の形が整うまで待ち、露出をアンダーに振って柔らかな光の層を残しています。",
      },
      {
        src: "/series-gallery/ueno-arcadia/ueno-arcadia-02.webp",
        alt: "木漏れ日がケージ越しに差し込む上野動物園の通路",
        width: 2560,
        height: 1707,
        contentLocation: "上野動物園",
        datePublished: "2025-05-24",
        caption: "ケージの影と光が織物のように揺れる。",
        statement:
          "格子の影が強かったので、コントラストを抑えて階調を残しました。来園者の足音が増える前に撮り終えるべく、手持ちで素早く構図を探っています。",
      },
      {
        src: "/series-gallery/ueno-arcadia/ueno-arcadia-03.webp",
        alt: "温室のガラスに広がる湿度の光が滲む上野動物園",
        width: 2560,
        height: 1706,
        contentLocation: "上野動物園",
        datePublished: "2025-05-24",
        caption: "湿度で曇ったガラスが光をやわらかく拡散する。",
        statement:
          "ガラスの水滴が描く模様を活かすため、ピントを手前に合わせて奥を柔らかく溶かしました。温室の蒸気でレンズが曇らないよう、都度クロスで拭きながら撮影しています。",
      },
      {
        src: "/series-gallery/ueno-arcadia/ueno-arcadia-04.webp",
        alt: "上野恩賜公園の池に映る冬晴れの空と樹木",
        width: 2560,
        height: 1707,
        contentLocation: "上野・浅草",
        datePublished: "2024-12-18",
        caption: "池の鏡面が冬の青をきりりと抱く。",
        statement:
          "風が止む一瞬を待ち、偏光を半分だけ効かせて反射と水中の色を両立させています。冬の硬い光を和らげるため、露出を抑えつつシャドウを後処理で丁寧に起こしました。",
      },
      {
        src: "/series-gallery/ueno-arcadia/ueno-arcadia-05.webp",
        alt: "上野恩賜公園の園路を彩る茶系の葉と手すり",
        width: 2560,
        height: 1707,
        contentLocation: "上野・浅草",
        datePublished: "2024-12-18",
        caption: "茶系の葉が冬の静寂を淡く彩る。",
        statement:
          "園路の曲線を活かすため、奥行きを詰める位置まで後退しました。枯葉のトーンが単調にならないよう、WBを少しだけ暖めて手すりの冷たさと対比させています。",
      },
      {
        src: "/series-gallery/ueno-arcadia/ueno-arcadia-06.webp",
        alt: "上野恩賜公園の石灯籠と縦に伸びる樹木を捉えた縦構図",
        width: 1707,
        height: 2560,
        contentLocation: "浅草",
        datePublished: "2024-12-28",
        caption: "石灯籠と樹木が冬の縦線を重ねる。",
        statement:
          "縦構図で高さを強調し、灯籠に当たる光が強すぎない位置を探りました。樹木の線が揃うよう何度も角度を変え、背景の建物が写り込まないポイントで切り取っています。",
      },
      {
        src: "/series-gallery/ueno-arcadia/ueno-arcadia-07.webp",
        alt: "井の頭恩賜公園の池に漂う薄霧とボートハウス",
        width: 2560,
        height: 1707,
        contentLocation: "井の頭公園",
        datePublished: "2025-01-13",
        caption: "薄霧がボートハウスを静かに包む午前。",
        statement:
          "霧が一番濃くなる時間帯を狙い、三脚を立てて微妙な揺らぎを捉えました。水鳥が入ると波紋が乱れるので、動きが落ち着くまでひたすら待ち続けています。",
      },
      {
        src: "/series-gallery/ueno-arcadia/ueno-arcadia-08.webp",
        alt: "井の頭恩賜公園の遊歩道を包む深い緑のトーン",
        width: 2560,
        height: 1707,
        contentLocation: "井の頭公園",
        datePublished: "2025-01-13",
        caption: "深い緑が都会の音をやさしく吸い込む。",
        statement:
          "遊歩道の湿度を表現したくて、WBを少しだけ緑寄りに振りました。落ち葉のハイライトを飛ばさないよう露出を抑え、画面全体のトーンを落ち着かせています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α1 II (ILCE-1M2)" },
      { label: "Lens", value: "FE 70-200mm F2.8 GM OSS II" },
      { label: "Settings", value: "1/640s · F2.8 · ISO 3200" },
    ],
    relatedCta: {
      heading: "公園ロケのご相談はこちら",
      body: "都市公園での撮影では、開園前後のローケーション確保から動植物への配慮まで一括でサポートします。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "canal-afterglow",
    title: "Canal Afterglow",
    year: 2025,
    location: "中目黒・代官山 · 代官山 · 目黒・品川",
    palette: "color",
    focus: "urban",
    synopsisEn: "Light along the canal from Nakameguro to Shinagawa — a slice of the fading city.",
    synopsis: "中目黒から品川へ続く運河沿いの光を集めた、暮れなずむ街のスライス。",
    lead: "目黒川沿いを歩きながら、夕暮れと夜の境界で街灯と水面が交わる瞬間を追いました。",
    story:
      "川面の反射を活かすため偏光フィルターでハイライトを整え、橋の上では手すりを前ボケに入れて立体感を作りました。広角と中望遠を切り替えながら、歩く速度に合わせてシャッタースピードを調整しています。",
    tags: ["Urban", "Twilight", "Waterfront"],
    cover: {
      src: "/series-gallery/canal-afterglow/canal-afterglow-01.webp",
      alt: "中目黒川沿いの水面に灯るライトの反射",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/canal-afterglow/canal-afterglow-01.webp",
      alt: "中目黒川沿いの水面に灯るライトの反射",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/canal-afterglow/canal-afterglow-01.webp",
        alt: "夕暮れの中目黒川に映り込む街灯と遊歩道",
        width: 2560,
        height: 1707,
        contentLocation: "中目黒・代官山",
        datePublished: "2024-09-13",
        caption: "夕暮れの川が街灯の色を抱いて揺れる。",
        statement:
          "中目黒川の水位が落ち着く時間を狙い、橋の上から反射が最も整う角度を探りました。偏光フィルターを半分だけ効かせ、川面の色と街灯の揺らぎを同時に残しています。",
      },
      {
        src: "/series-gallery/canal-afterglow/canal-afterglow-02.webp",
        alt: "代官山の路地に連なるライトと木々のシルエット",
        width: 2560,
        height: 1707,
        contentLocation: "中目黒・代官山",
        datePublished: "2024-09-13",
        caption: "路地のライトが木々の影を導く。",
        statement:
          "路地の奥行きを感じてもらえるよう、ローアングルでライトの連なりを強調しました。交通量が増える前に撮り終えるため、フットワークを軽くして複数ポイントを周回しています。",
      },
      {
        src: "/series-gallery/canal-afterglow/canal-afterglow-03.webp",
        alt: "中目黒の高架下を彩る暖色のサインと通り",
        width: 2560,
        height: 1707,
        contentLocation: "中目黒・代官山",
        datePublished: "2024-09-13",
        caption: "暖色のサインが夜を迎える支度をする。",
        statement:
          "ネオンの色が強すぎるので、ホワイトバランスを少し冷やして暖色を落ち着かせました。高架下の動きが出るよう、シャッターを1/30秒に落として人の気配を僅かに残しています。",
      },
      {
        src: "/series-gallery/canal-afterglow/canal-afterglow-04.webp",
        alt: "恵比寿から中目黒へ続く川沿いを見下ろした縦構図",
        width: 2048,
        height: 2560,
        contentLocation: "代官山",
        datePublished: "2025-02-10",
        caption: "橋の上から眺める川が街を静かに分ける。",
        statement:
          "縦構図で距離感を出すため、橋の真ん中から中望遠で切り取りました。手前の手すりを避けるために体を少し乗り出し、水平が傾かないよう慎重に構えています。",
      },
      {
        src: "/series-gallery/canal-afterglow/canal-afterglow-05.webp",
        alt: "遊歩道に沿って淡く灯るランタンと川面",
        width: 2560,
        height: 1707,
        contentLocation: "代官山",
        datePublished: "2025-02-10",
        caption: "ランタンの灯が川辺をそっと彩る。",
        statement:
          "ランタンの光量が揃うタイミングを確認し、光のリズムが途切れない位置から撮影しました。側溝の白線が写り込まないよう、足場を調整して画面を整えています。",
      },
      {
        src: "/series-gallery/canal-afterglow/canal-afterglow-06.webp",
        alt: "橋の上から縦に切り取った夜の中目黒川",
        width: 1707,
        height: 2560,
        contentLocation: "代官山",
        datePublished: "2025-02-10",
        caption: "縦に切り取ることで川のリズムが延びていく。",
        statement:
          "橋の中央で真下を向き、手すりに体を預けて手ぶれを抑えました。車のテールライトが重なる瞬間を狙い、露出を少し長めにして光の筋を伸ばしています。",
      },
      {
        src: "/series-gallery/canal-afterglow/canal-afterglow-07.webp",
        alt: "目黒と品川を結ぶ線路脇に伸びるテールライト",
        width: 1707,
        height: 2560,
        contentLocation: "目黒・品川",
        datePublished: "2025-06-07",
        caption: "線路脇のテールライトが都市の脈を描く。",
        statement:
          "車列の間隔が安定する時間帯を狙い、1秒露光でテールライトを伸ばしました。線路のバラストが乱雑にならないよう、前景を斜めに入れて奥行きを作っています。",
      },
      {
        src: "/series-gallery/canal-afterglow/canal-afterglow-08.webp",
        alt: "品川方面へ続く水路と高層ビルの夜景",
        width: 1707,
        height: 2560,
        contentLocation: "目黒・品川",
        datePublished: "2025-06-07",
        caption: "水路が夜景の光をすくい取りながら湾へ流れる。",
        statement:
          "ビルの灯りが水面に落ちる角度を確かめ、視線が奥へ進むよう縦構図でラインを強調しました。フェンス越しの撮影だったため、レンズの前に黒布をかけて反射を抑えています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 24-70mm F2.8 GM II" },
      { label: "Settings", value: "1/500s · F2.8 · ISO 100" },
    ],
    relatedCta: {
      heading: "街歩きロケのご相談はこちら",
      body: "ナイトロケでは水辺や路地を組み合わせたプランニングと、移動導線の安全管理まで対応します。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "asakusa-promenade",
    title: "Asakusa Promenade",
    year: 2024,
    location: "浅草 · 上野・浅草",
    palette: "color",
    focus: "urban",
    synopsisEn: "Asakusa's alleys and temples, drawn in lantern light and morning mist.",
    synopsis: "浅草の路地と寺社を、提灯の光と朝霧で描いた町歩きシリーズ。",
    lead: "夜明け前から浅草寺界隈を巡り、提灯の灯りが消えるまでの短い時間を切り取りました。",
    story:
      "混雑を避けるため夜明け前に入り、仲見世の明暗差はHDRではなく2段マイナスで撮影して後処理で持ち上げています。提灯の質感を活かすため、色温度は3500K付近で固定しました。",
    tags: ["Urban", "Night", "Culture"],
    cover: {
      src: "/series-gallery/asakusa-promenade/asakusa-promenade-01.webp",
      alt: "浅草寺の参道に並ぶ提灯と湿った石畳",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/asakusa-promenade/asakusa-promenade-01.webp",
      alt: "浅草寺の参道に並ぶ提灯と湿った石畳",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/asakusa-promenade/asakusa-promenade-01.webp",
        alt: "浅草寺の参道を照らす提灯と濡れた石畳",
        width: 2560,
        height: 1707,
        contentLocation: "浅草",
        datePublished: "2024-12-28",
        caption: "提灯の光が雨上がりの参道を染める。",
        statement:
          "夜明け前の雨で石畳が艶を持った瞬間を狙い、提灯の列が途切れない位置に立ちました。色温度を3500Kに固定し、朱色の飽和を抑えながら湿度を残しています。",
      },
      {
        src: "/series-gallery/asakusa-promenade/asakusa-promenade-02.webp",
        alt: "仲見世のアーケードを縦構図で捉えた夜明け前の光",
        width: 1707,
        height: 2560,
        contentLocation: "浅草",
        datePublished: "2024-12-28",
        caption: "アーケードの奥に朝の青が溶けていく。",
        statement:
          "縦構図で奥行きを強調し、店舗のシャッターが均一なリズムになるタイミングを待ちました。通行人が入らない早朝に撮影し、シャッター速度を落として薄明かりの質感を残しています。",
      },
      {
        src: "/series-gallery/asakusa-promenade/asakusa-promenade-03.webp",
        alt: "浅草寺本堂を包む柔らかな霧と朱色の装飾",
        width: 2560,
        height: 1707,
        contentLocation: "浅草",
        datePublished: "2024-12-28",
        caption: "霧が本堂の朱をやわらかく包み込む。",
        statement:
          "霧が動くたびに装飾の見え方が変わるので、ピントを手前に置いて奥のディテールを柔らかくしました。参拝客が現れる前に、三脚を使わず機動力を優先しています。",
      },
      {
        src: "/series-gallery/asakusa-promenade/asakusa-promenade-04.webp",
        alt: "雷門前の交差点に残る夜の余韻",
        width: 2560,
        height: 1707,
        contentLocation: "浅草",
        datePublished: "2024-12-28",
        caption: "雷門の朱と信号の青が夜の余韻を奏でる。",
        statement:
          "交差点の信号サイクルを読みながら、車のテールライトが綺麗に抜けるタイミングを合わせました。広角で歪み過ぎないよう慎重に立ち位置を調整し、提灯の明かりを画面に散らせています。",
      },
      {
        src: "/series-gallery/asakusa-promenade/asakusa-promenade-05.webp",
        alt: "浅草の路地に灯る赤提灯と暖簾",
        width: 2560,
        height: 1707,
        contentLocation: "上野・浅草",
        datePublished: "2024-12-18",
        caption: "路地の赤提灯が夜更けの余熱を残す。",
        statement:
          "人通りが少ない時間帯に、暖簾が風で揺れる瞬間を狙いました。赤の飽和を抑えるために露出を-1EVにし、背景の暗部をほんの少しだけ持ち上げています。",
      },
      {
        src: "/series-gallery/asakusa-promenade/asakusa-promenade-06.webp",
        alt: "仲見世の縦構図で捉えた提灯の連なり",
        width: 1707,
        height: 2560,
        contentLocation: "上野・浅草",
        datePublished: "2024-12-18",
        caption: "提灯の列が空へ伸びる祈りのリズム。",
        statement:
          "縦に長い列を強調するため、広角で歪みをコントロールしながら中央に立ちました。テープライトの色が偏りすぎないようホワイトバランスを微調整しています。",
      },
      {
        src: "/series-gallery/asakusa-promenade/asakusa-promenade-07.webp",
        alt: "浅草寺境内の石畳に映る金色の光",
        width: 2560,
        height: 1707,
        contentLocation: "上野・浅草",
        datePublished: "2024-12-18",
        caption: "石畳に映る金色が静かな時間を照らす。",
        statement:
          "路面の反射を活かすため、低い位置から石畳を斜めに切り取りました。ハイライトが飛ばないよう露出を抑え、金色の輝きが滑らかになる位置を選んでいます。",
      },
      {
        src: "/series-gallery/asakusa-promenade/asakusa-promenade-08.webp",
        alt: "浅草の商店街に漂う夜明け前の青",
        width: 1707,
        height: 2560,
        contentLocation: "上野・浅草",
        datePublished: "2024-12-18",
        caption: "夜明け前の蒼が商店街に静けさを落とす。",
        statement:
          "空の青が残る時間帯を狙い、商店街の看板が一斉に点灯する瞬間を押さえました。奥行きを出すために望遠で圧縮し、手前の軒先をわずかに前ボケさせています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 III (ILCE-7M3)" },
      { label: "Lens", value: "FE 85mm F1.8" },
      { label: "Settings", value: "1/800s · F9 · ISO 2500" },
    ],
    relatedCta: {
      heading: "寺社ロケーション撮影のご相談",
      body: "歴史的エリアでの撮影では、時間帯の許可取りや混雑回避の導線設計までお任せください。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "yoyogi-intervals",
    title: "Yoyogi Intervals",
    year: 2025,
    location: "新宿〜渋谷 · 渋谷・新宿 · 新宿御苑・代々木",
    palette: "color",
    focus: "nature",
    synopsisEn: "Circling Yoyogi to Shinjuku, where the city's green takes a breath.",
    synopsis: "代々木から新宿を回遊し、都市の緑が呼吸する瞬間を集めた歩行シリーズ。",
    lead: "代々木と新宿の公園を歩きながら、都市のリズムと緑の間に生まれる間合いを記録しました。",
    story:
      "歩行スナップでは1/320s前後で被写体の揺れを抑えつつ、木々の葉を透過する光を拾うため露出を若干アンダーに設定。園内では望遠で層を積み重ね、歩道ではローアングルで距離感を出しました。",
    tags: ["Nature", "Urban", "Walk"],
    cover: {
      src: "/series-gallery/yoyogi-intervals/yoyogi-intervals-01.webp",
      alt: "代々木公園の芝生に伸びる朝の影",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/yoyogi-intervals/yoyogi-intervals-01.webp",
      alt: "代々木公園の芝生に伸びる朝の影",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/yoyogi-intervals/yoyogi-intervals-01.webp",
        alt: "代々木公園の芝生と遠景のビル群を結ぶ朝の光",
        width: 2560,
        height: 1707,
        contentLocation: "新宿〜渋谷",
        datePublished: "2024-09-07",
        caption: "芝生の朝露がビルの光と手を取り合う。",
        statement:
          "芝生の露が太陽を反射するタイミングを狙い、ローアングルでビルとの距離感を詰めました。風が吹くと露が消えるので、呼吸を合わせて一瞬で切り取っています。",
      },
      {
        src: "/series-gallery/yoyogi-intervals/yoyogi-intervals-02.webp",
        alt: "代々木の木々を縦構図で切り取った並木道",
        width: 1707,
        height: 2560,
        contentLocation: "新宿〜渋谷",
        datePublished: "2024-09-07",
        caption: "縦に連なる幹が朝の空気を吸い込む。",
        statement:
          "並木の間隔が均一に見える位置まで歩き、縦構図で高さを強調しました。木漏れ日のハイライトが飛ばないよう、露出を-2/3EVに設定しています。",
      },
      {
        src: "/series-gallery/yoyogi-intervals/yoyogi-intervals-03.webp",
        alt: "笹塚から代々木へ続く歩道橋を照らす午後の光",
        width: 2048,
        height: 2560,
        contentLocation: "渋谷・新宿",
        datePublished: "2025-02-01",
        caption: "歩道橋の影がまち歩きのテンポを刻む。",
        statement:
          "歩道橋の構造を活かすため、音のリズムが聞こえるような距離まで下がりました。光が鉄骨に落ちる角度を確認し、グラデーションが最も美しい時間に合わせています。",
      },
      {
        src: "/series-gallery/yoyogi-intervals/yoyogi-intervals-04.webp",
        alt: "代々木エリアの商店街を俯瞰した縦構図",
        width: 1707,
        height: 2560,
        contentLocation: "渋谷・新宿",
        datePublished: "2025-02-01",
        caption: "俯瞰の視線が商店街の密度を紡ぐ。",
        statement:
          "高架から俯瞰で撮影し、商店街の看板がリズミカルに並ぶ位置を探しました。人の流れが分かるよう、シャッターを少しだけ遅くして動きを残しています。",
      },
      {
        src: "/series-gallery/yoyogi-intervals/yoyogi-intervals-05.webp",
        alt: "新宿御苑の並木道を透過する春の光",
        width: 1707,
        height: 2560,
        contentLocation: "新宿御苑・代々木",
        datePublished: "2025-03-20",
        caption: "春の光が並木を透過して柔らかな幕を作る。",
        statement:
          "逆光で葉が透ける時間帯に合わせ、F5.6で奥のボケを適度に保ちました。観光客が入らないよう隙間を狙い、リズムを崩さない位置で静かに待っています。",
      },
      {
        src: "/series-gallery/yoyogi-intervals/yoyogi-intervals-06.webp",
        alt: "新宿御苑の池に映る桜色のグラデーション",
        width: 2560,
        height: 1707,
        contentLocation: "新宿御苑・代々木",
        datePublished: "2025-03-20",
        caption: "池に映った桜色がぼんやりと揺れる。",
        statement:
          "水面の反射を拾うため、風が落ち着くタイミングを待って1/8秒に設定しました。露出を少しアンダーにして、グラデーションの階調を丁寧に残しています。",
      },
      {
        src: "/series-gallery/yoyogi-intervals/yoyogi-intervals-07.webp",
        alt: "新宿中央公園のベンチと背後にそびえる高層ビル",
        width: 1707,
        height: 2560,
        contentLocation: "新宿中央公園",
        datePublished: "2024-05-11",
        caption: "ベンチの静けさを高層ビルが見守る。",
        statement:
          "都市と公園の対比を描くため、望遠で圧縮しながらベンチを手前に配置しました。夕方の光でコントラストが強かったので、WBを少しだけ冷やして落ち着いたトーンに整えています。",
      },
      {
        src: "/series-gallery/yoyogi-intervals/yoyogi-intervals-08.webp",
        alt: "駒沢公園のランニングトラックと夕方の木漏れ日",
        width: 2560,
        height: 1707,
        contentLocation: "駒沢公園",
        datePublished: "2024-11-04",
        caption: "ランニングトラックに夕方の木漏れ日が差し込む。",
        statement:
          "ランナーの流れを邪魔しないよう端から撮影し、木漏れ日がトラックのカーブをなぞる時間を待ちました。木々のグリーンが沈みすぎないよう、彩度をわずかにキープしています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 70-200mm F2.8 GM OSS II" },
      { label: "Settings", value: "1/320s · F5 · ISO 100" },
    ],
    relatedCta: {
      heading: "ロケハン同行のご相談",
      body: "街と緑が交差するエリアでの撮影では、歩行導線の確保や許認可の確認までまとめてサポートします。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "matsuyama-transit",
    title: "Matsuyama Transit",
    year: 2025,
    location: "松山",
    palette: "color",
    focus: "urban",
    synopsisEn: "Matsuyama's trams and shopping streets, caught between business trips.",
    synopsis: "松山のトラムと商店街をめぐり、出張の合間に切り取った街の息遣い。",
    lead: "松山市内を移動しながら、路面電車と路地が交差する瞬間をスナップしました。",
    story:
      "移動時間の合間に撮影するため、ボディは軽量セットで統一。光が回りやすい午前は露出をマイナス補正し、夜はLEDの色偏りを整えるためにカスタムWBを使用しました。",
    tags: ["Travel", "Urban", "Street"],
    cover: {
      src: "/series-gallery/matsuyama-transit/matsuyama-transit-01.webp",
      alt: "松山市内を走る路面電車と濡れた路面",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/matsuyama-transit/matsuyama-transit-01.webp",
      alt: "松山市内を走る路面電車と濡れた路面",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/matsuyama-transit/matsuyama-transit-01.webp",
        alt: "松山の路面電車が交差点を曲がる瞬間",
        width: 2560,
        height: 1707,
        contentLocation: "松山",
        datePublished: "2025-03-13",
        caption: "路面電車のカーブが市街地の呼吸を描く。",
        statement:
          "交差点の信号待ちで時間が限られていたので、構図を事前に決めて待ちました。濡れた路面が光を拾う瞬間を狙い、シャッター速度を1/125秒に保っています。",
      },
      {
        src: "/series-gallery/matsuyama-transit/matsuyama-transit-02.webp",
        alt: "松山の商店街に差し込む縦構図の朝光",
        width: 1707,
        height: 2560,
        contentLocation: "松山",
        datePublished: "2025-03-13",
        caption: "商店街の奥へ朝光がすっと差し込む。",
        statement:
          "出張の合間に訪れたため時間が限られていましたが、光が最も美しく差し込む位置を探って縦構図で切り取りました。人の流れが自然に写るよう、連写ではなく呼吸を合わせています。",
      },
      {
        src: "/series-gallery/matsuyama-transit/matsuyama-transit-03.webp",
        alt: "濡れた石畳に映るネオンと人影",
        width: 1707,
        height: 2560,
        contentLocation: "松山",
        datePublished: "2025-03-13",
        caption: "ネオンが石畳に滲み、人影がそっと交差する。",
        statement:
          "夜の雨上がりに石畳が鏡のようになった瞬間を狙い、シャッターを1/40秒に落として人影のブレを活かしました。色偏りを抑えるため、ホワイトバランスを店舗の光より少し冷たく設定しています。",
      },
      {
        src: "/series-gallery/matsuyama-transit/matsuyama-transit-04.webp",
        alt: "松山城下の坂道を進む路面電車",
        width: 2560,
        height: 1707,
        contentLocation: "松山",
        datePublished: "2025-03-13",
        caption: "坂道を登る電車が街の時間を刻む。",
        statement:
          "坂道の勾配を見せるため、サイドからの角度を選びました。車体の色が鮮やかに出るよう曇天でも露出をプラスに振り、背景の建物がうるさくならない距離を確保しています。",
      },
      {
        src: "/series-gallery/matsuyama-transit/matsuyama-transit-05.webp",
        alt: "松山市内の交差点に立つ黄昏のシルエット",
        width: 2560,
        height: 1707,
        contentLocation: "松山",
        datePublished: "2025-03-13",
        caption: "黄昏の交差点で光がシルエットを浮かび上がらせる。",
        statement:
          "斜光が人影を長く伸ばす時間帯に合わせて待ち、露出を-1EVにして空の彩度を保ちました。信号の色が画面にバランスよく入るよう、立ち位置を微調整しています。",
      },
      {
        src: "/series-gallery/matsuyama-transit/matsuyama-transit-06.webp",
        alt: "松山のアーケード商店街に並ぶ看板と人の流れ",
        width: 2560,
        height: 1707,
        contentLocation: "松山",
        datePublished: "2025-03-13",
        caption: "アーケードの看板と人流がリズムを刻む。",
        statement:
          "天井の照明が均一になる位置を探し、看板のリズムが揃うフレームを選びました。歩行者の流れが重なりすぎないよう、シャッターを1/60秒にして程よい動きを残しています。",
      },
      {
        src: "/series-gallery/matsuyama-transit/matsuyama-transit-07.webp",
        alt: "出張の拠点となったホテル前に停車する路面電車",
        width: 1707,
        height: 2560,
        contentLocation: "松山",
        datePublished: "2025-03-13",
        caption: "ホテル前で電車が一日の終わりを告げる。",
        statement:
          "宿泊先の前を通る最終便に合わせ、ホテルの灯りと車両のライトが調和する時間を狙いました。手持ちでブレないギリギリのシャッター速度に設定し、個人的な旅路の記憶を重ねています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α1 II (ILCE-1M2)" },
      { label: "Lens", value: "FE 24-70mm F2.8 GM" },
      { label: "Settings", value: "1/250s · F8 · ISO 2500" },
    ],
    relatedCta: {
      heading: "出張同行撮影のご相談",
      body: "移動を伴う案件では、スケジュール管理やバックアップ体制まで含めたロケ構成をご提案します。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "kudan-layers",
    title: "Kudan Layers",
    year: 2024,
    location: "九段下・市ヶ谷 · 市ヶ谷・飯田橋 · 新宿",
    palette: "color",
    focus: "urban",
    synopsisEn: "Looking from Kudanshita toward Shinjuku, layering dawn and nightscape.",
    synopsis: "九段下から新宿を見晴らし、夜明けと夜景のレイヤーを重ねたシリーズ。",
    lead: "九段下の坂と水辺、新宿の展望から都市の層を眺め、夜と朝の質感を対比させました。",
    story:
      "夜景は三脚を使わず手持ちで1/200sまで落とし、ISOを上げながらもネオンの色を保持。朝はNDフィルターで空の輝度を抑え、露出ブラケットを最小限に留めています。",
    tags: ["Urban", "Night", "Viewpoint"],
    cover: {
      src: "/series-gallery/kudan-layers/kudan-layers-01.webp",
      alt: "九段下の堀沿いに伸びるライトトレイル",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/kudan-layers/kudan-layers-01.webp",
      alt: "九段下の堀沿いに伸びるライトトレイル",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/kudan-layers/kudan-layers-01.webp",
        alt: "九段下の堀と車列が描くライトトレイル",
        width: 2560,
        height: 1707,
        contentLocation: "九段下・市ヶ谷",
        datePublished: "2024-10-25",
        caption: "堀のラインにライトトレイルが重なり都市が目を覚ます。",
        statement:
          "首都高と堀のカーブが揃う位置を探し、車列のリズムが整うまで1/2秒で粘りました。堀の暗部が潰れないよう露出を調整し、水面の反射を丁寧に残しています。",
      },
      {
        src: "/series-gallery/kudan-layers/kudan-layers-02.webp",
        alt: "九段坂のカーブを流れるヘッドライト",
        width: 2560,
        height: 1707,
        contentLocation: "九段下・市ヶ谷",
        datePublished: "2024-10-25",
        caption: "ヘッドライトが坂道の呼吸をなぞる。",
        statement:
          "九段坂の勾配が伝わる角度まで移動し、ライトが途切れないタイミングを待ちました。歩道の柵がフレームに入らない位置で三脚を低く構え、車の流れを滑らかに捉えています。",
      },
      {
        src: "/series-gallery/kudan-layers/kudan-layers-03.webp",
        alt: "靖国通り越しに望む夜の都心",
        width: 2560,
        height: 1707,
        contentLocation: "九段下・市ヶ谷",
        datePublished: "2024-10-25",
        caption: "靖国通りのラインが都心の夜景を引き寄せる。",
        statement:
          "遠景のビルをすっきり見せるため、望遠で圧縮して道路のラインを主役にしました。手前の街灯が強すぎたので、フードで遮光しながら光のバランスを整えています。",
      },
      {
        src: "/series-gallery/kudan-layers/kudan-layers-04.webp",
        alt: "九段会館をかすめる車の光跡",
        width: 2560,
        height: 1707,
        contentLocation: "九段下・市ヶ谷",
        datePublished: "2024-10-25",
        caption: "歴史ある建物を光跡がそっと縁取る。",
        statement:
          "九段会館の重厚感を損なわないよう、光跡が建物をなでる角度を選びました。露光時間を短めにし、建物のディテールがブレずに残るギリギリを狙っています。",
      },
      {
        src: "/series-gallery/kudan-layers/kudan-layers-05.webp",
        alt: "皇居外苑を走る車列と堀の反射",
        width: 2560,
        height: 1707,
        contentLocation: "九段下・市ヶ谷",
        datePublished: "2024-10-25",
        caption: "皇居の外堀がライトの帯を受け止める。",
        statement:
          "堀の反射と車列が同時に見える高さを探し、三脚の脚を最大まで伸ばしました。風で水面が揺れる前に1/3秒で撮影し、夜の静けさと動きを同居させています。",
      },
      {
        src: "/series-gallery/kudan-layers/kudan-layers-06.webp",
        alt: "九段下の朝靄を抜ける通勤自転車",
        width: 1707,
        height: 2560,
        contentLocation: "市ヶ谷・飯田橋",
        datePublished: "2024-11-22",
        caption: "朝靄を切り裂く自転車の音まで聴こえる。",
        statement:
          "靄が出る条件を予報で確認し、自転車通勤が増える時間に合わせました。逆光で靄の粒が浮かぶよう、露出を抑えつつシャッターを1/250秒に設定しています。",
      },
      {
        src: "/series-gallery/kudan-layers/kudan-layers-07.webp",
        alt: "日の出の光が差す九段下の交差点",
        width: 1707,
        height: 2560,
        contentLocation: "市ヶ谷・飯田橋",
        datePublished: "2024-11-22",
        caption: "交差点に朝日が射し込み街の動脈が目を覚ます。",
        statement:
          "ビルの隙間から差す朝日が路面を照らす瞬間を狙い、信号の色が揃うタイミングを待ちました。露出をアンダーにして光の線を引き締め、都市の始動感を残しています。",
      },
      {
        src: "/series-gallery/kudan-layers/kudan-layers-08.webp",
        alt: "九段会館前に差し込む斜光と歩行者",
        width: 1707,
        height: 2560,
        contentLocation: "市ヶ谷・飯田橋",
        datePublished: "2024-11-22",
        caption: "斜光が歩行者の輪郭を引き出す午前。",
        statement:
          "通勤者が一定のリズムで歩く時間帯を選び、斜光が足元に伸びる影を強調しました。背景の看板が目立たないよう、構図を少し傾けて整理しています。",
      },
      {
        src: "/series-gallery/kudan-layers/kudan-layers-09.webp",
        alt: "新宿の超高層ビルを見渡す夕方の展望",
        width: 1707,
        height: 2560,
        contentLocation: "新宿",
        datePublished: "2025-08-10",
        caption: "夕暮れの空が超高層の輪郭をやわらかく包む。",
        statement:
          "展望室のガラス越しだったので、反射を避けるために黒布でレンズ周りを覆いました。夕陽がビルに反射する瞬間を待ち、色が飽和しすぎないよう露出を微調整しています。",
      },
      {
        src: "/series-gallery/kudan-layers/kudan-layers-10.webp",
        alt: "夕焼けに染まる新宿副都心のライン",
        width: 1707,
        height: 2560,
        contentLocation: "新宿",
        datePublished: "2025-08-10",
        caption: "夕焼けが副都心をオレンジのシルエットに変える。",
        statement:
          "日没直後のマジックアワーを逃さないよう、露出を少しアンダーに振りながら空の色を残しました。ビルのラインが整う位置を探り、三脚禁止エリアなので手すりに肘を固定しています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "50mm F1.4 DG HSM | Art 018" },
      { label: "Settings", value: "1/200s · F1.4 · ISO 5000" },
    ],
    relatedCta: {
      heading: "夜景・展望撮影のご相談",
      body: "展望施設や坂道での撮影では、三脚制限への対応や時間帯の調整を含めたプランをご提案します。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
  {
    slug: "first-light-voyage",
    title: "First Light Voyage",
    year: 2025,
    location: "日出づる里 · 東京駅 · 浜松町",
    palette: "color",
    focus: "people",
    synopsisEn: "From first sunrise to the waking, pre-commute city — a morning journey.",
    synopsis: "初日の出から通勤前の都市が目覚めるまでの光を追ったモーニングジャーニー。",
    lead: "夜明け前の日出づる里から、目覚めていく都内の動線までを巡り、日が昇るにつれて変わる空気感と人の流れを収集したシリーズ。",
    story:
      "山梨・富士川町の髙下（日出づる里）で、富士山頂に太陽が重なるダイヤモンド富士を待った後、東京駅や浜松町、渋谷の朝へと移動し、光の角度と人のテンポが連続して変化する時間帯を追いかけました。露出とホワイトバランスを細かく調整しながら、柔らかい朝のハイライトを残しています。",
    tags: ["Morning", "People", "Travel"],
    cover: {
      src: "/series-gallery/first-light-voyage/first-light-voyage-01.webp",
      alt: "日出づる里で迎えた初日の出",
      width: 2560,
      height: 1707,
    },
    heroImage: {
      src: "/series-gallery/first-light-voyage/first-light-voyage-02.webp",
      alt: "日出づる里で迎えた初日の出 2",
      width: 2560,
      height: 1707,
    },
    gallery: [
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-01.webp",
        alt: "日出づる里で迎えた初日の出",
        width: 2560,
        height: 1707,
        contentLocation: "日出づる里",
        datePublished: "2025-01-01",
        caption: "富士の稜線に、最初の光が触れる。",
        statement:
          "夜明け前に立ち位置を決め、富士山頂と太陽が重なる一瞬を待ちました。冷え込みで曇る前玉をこまめに拭き、稜線と空のグラデーションを丁寧に残しています。",
      },
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-02.webp",
        alt: "日出づる里で迎えた初日の出 2",
        width: 2560,
        height: 1707,
        contentLocation: "日出づる里",
        datePublished: "2025-01-01",
        caption: "山際が、ゆっくりと金色に染まっていく。",
        statement:
          "逆光が人の背中に落ちる位置まで移動し、フレアを抑えるため露出を-0.7EVに調整しました。頂に光が乗るまでの時間を数えながら、待つ人の気配が途切れない瞬間で切り取っています。",
      },
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-03.webp",
        alt: "日出づる里で迎えた初日の出 3",
        width: 2560,
        height: 1707,
        contentLocation: "日出づる里",
        datePublished: "2025-01-01",
        caption: "頂の上に、新年の光がひとつ立つ。",
        statement:
          "空の輝度を抑えたくてハーフNDを使い、山肌のディテールを残しながら光の芯を浮かび上がらせました。三脚を低く構え、人影が重ならない瞬間を狙っています。",
      },
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-04.webp",
        alt: "日出づる里で迎えた初日の出 4",
        width: 2560,
        height: 1707,
        contentLocation: "日出づる里",
        datePublished: "2025-01-01",
        caption: "凍える空気の中、光だけが暖かい。",
        statement:
          "シャッター速度を上げて山際の光を締めつつ、朝焼けの色を保ちました。冷たい風の中、頂に光が乗る瞬間を望遠で引き寄せています。",
      },
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-05.webp",
        alt: "始発直後の東京駅周辺",
        width: 2560,
        height: 1707,
        contentLocation: "東京駅",
        datePublished: "2024-10-31",
        caption: "丸の内の煉瓦に朝の朱が差し込む。",
        statement:
          "駅舎のライトと朝焼けのバランスを保つため、ホワイトバランスを太陽光に固定してRAW現像前提で露出を整えました。三脚禁止エリアなので胸の高さで構え、ブレないギリギリの速度を維持しています。",
      },
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-06.webp",
        alt: "始発直後の東京駅周辺 2",
        width: 2560,
        height: 1707,
        contentLocation: "東京駅",
        datePublished: "2024-10-31",
        caption: "石畳の影が目覚めのテンポを刻む。",
        statement:
          "影の角度が最も美しく伸びる位置まで歩き、路面の湿りが反射する時間帯を選びました。人の歩みが自然に写るよう連写を使わず、呼吸を合わせたワンショットに集中しています。",
      },
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-07.webp",
        alt: "始発直後の東京駅周辺 3",
        width: 2560,
        height: 1707,
        contentLocation: "東京駅",
        datePublished: "2024-10-31",
        caption: "駅舎のアーチを朝光が縁取る。",
        statement:
          "アーチのラインが歪まない焦点距離を選び、中央に立って左右のバランスを取りました。空の淡いブルーと窓明かりの差を残すため露出を少しアンダーに設定しています。",
      },
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-08.webp",
        alt: "浜松町の高架と街路に差す朝日",
        width: 2560,
        height: 1707,
        contentLocation: "浜松町",
        datePublished: "2025-01-26",
        caption: "高架の影が街路に柔らかな呼吸を残す。",
        statement:
          "朝日が首都高の梁に沿って流れる角度を前日ロケで確認し、ローアングルからラインを拾いました。車列が消える一瞬を待ち、ISOを上げすぎない範囲でシャッター速度を確保しています。",
      },
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-09.webp",
        alt: "浜松町の高架と街路に差す朝日 2",
        width: 2048,
        height: 2560,
        contentLocation: "浜松町",
        datePublished: "2025-01-26",
        caption: "逆光に浮かぶ歩道橋のシルエット。",
        statement:
          "歩道橋の階段を駆け上がり、逆光で人物が浮かぶ位置を探りました。シャッターを1/500秒に固定してブレを抑え、光のフレアをほんの少し残すことで朝の眩しさを表現しています。",
      },
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-10.webp",
        alt: "浜松町の高架と街路に差す朝日 3",
        width: 2560,
        height: 1707,
        contentLocation: "浜松町",
        datePublished: "2025-01-26",
        caption: "首都高の陰が街路を静かに区切る。",
        statement:
          "交通量が増える前に信号のサイクルを見極め、車列が途切れる瞬間を待ちました。アスファルトの質感を出すため露出をマイナス補正し、光と影の境界を際立たせています。",
      },
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-11.webp",
        alt: "渋谷の朝活コミュニティ",
        width: 2560,
        height: 1707,
        contentLocation: "渋谷",
        datePublished: "2025-01-12",
        caption: "朝活の輪が会場の温度を上げていく。",
        statement:
          "コミュニティの空気感を壊さないよう距離を保ち、85mmで圧縮して場の熱量を拾いました。自然光と室内照明の色差を整えるためカスタムWBを設定しています。",
      },
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-12.webp",
        alt: "渋谷の朝活コミュニティ 2",
        width: 1707,
        height: 2560,
        contentLocation: "渋谷",
        datePublished: "2025-01-12",
        caption: "窓辺の光が会話をやさしく照らす。",
        statement:
          "窓から差す光が揃うタイミングを待ち、露出を-0.3EVにして肌のハイライトを守りました。参加者同士の視線が交わる瞬間を狙い、連写ではなく一枚に集中しています。",
      },
      {
        src: "/series-gallery/first-light-voyage/first-light-voyage-13.webp",
        alt: "渋谷の朝活コミュニティ 3",
        width: 2560,
        height: 1707,
        contentLocation: "渋谷",
        datePublished: "2025-01-12",
        caption: "ペンとノートが光に染まり始業を告げる。",
        statement:
          "テーブル上の小物のリズムを意識し、斜め上から俯瞰気味に構図を決定しました。ISOを少し上げてシャッター速度を確保し、自然な手の動きを残しています。",
      },
    ],
    exif: [
      { label: "Camera", value: "Sony α7 IV (ILCE-7M4)" },
      { label: "Lens", value: "FE 70-200mm F2.8 GM OSS II" },
      { label: "Settings", value: "1/500s · F3.5 · ISO 5000" },
    ],
    relatedCta: {
      heading: "撮影のご相談はこちら",
      body: "シリーズに合わせたロケーション提案やスケジュール設計から撮影・納品まで一貫して対応します。",
      href: "/services",
      label: "Servicesを見る",
    },
  },
];

export const seriesDetails: SeriesDetails[] = [...baseSeriesDetails, ...unusedSeriesDetails];

export function getSeriesBySlug(slug: string) {
  return seriesDetails.find((series) => series.slug === slug);
}
